project_id = "chojxtvzspqqzsmwcbul"

[functions]
  verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.discord-bot]
    verify_jwt = false
  [functions.get-affiliate-config]
    verify_jwt = false
  [functions.prerender]
    verify_jwt = false
  [functions.sitemap]
    verify_jwt = false
