// AUTO-GENERATED by scripts/generate-set-vocabulary.mjs — do not edit by hand.
// Source: https://api.scryfall.com/sets
// Regenerate with: node scripts/generate-set-vocabulary.mjs

export interface ScryfallSetEntry {
  /** Scryfall set code, lowercase (e.g. "hob"). */
  code: string;
  /** Official set name (e.g. "The Hobbit"). */
  name: string;
  /** Scryfall set_type (expansion, commander, eternal, ...). */
  setType: string;
  /** ISO release date; may be in the future for announced sets. */
  releasedAt: string | null;
  /** Parent set code for supplemental products (commander decks, etc). */
  parentSetCode: string | null;
}

export const SCRYFALL_SETS: readonly ScryfallSetEntry[] = [
  {
    "code": "10e",
    "name": "Tenth Edition",
    "setType": "core",
    "releasedAt": "2007-07-13",
    "parentSetCode": null
  },
  {
    "code": "2ed",
    "name": "Unlimited Edition",
    "setType": "core",
    "releasedAt": "1993-12-01",
    "parentSetCode": null
  },
  {
    "code": "2x2",
    "name": "Double Masters 2022",
    "setType": "masters",
    "releasedAt": "2022-07-08",
    "parentSetCode": null
  },
  {
    "code": "2xm",
    "name": "Double Masters",
    "setType": "masters",
    "releasedAt": "2020-08-07",
    "parentSetCode": null
  },
  {
    "code": "3ed",
    "name": "Revised Edition",
    "setType": "core",
    "releasedAt": "1994-04-11",
    "parentSetCode": null
  },
  {
    "code": "40k",
    "name": "Warhammer 40,000 Commander",
    "setType": "commander",
    "releasedAt": "2022-10-07",
    "parentSetCode": null
  },
  {
    "code": "4bb",
    "name": "Fourth Edition Foreign Black Border",
    "setType": "core",
    "releasedAt": "1995-04-01",
    "parentSetCode": "4ed"
  },
  {
    "code": "4ed",
    "name": "Fourth Edition",
    "setType": "core",
    "releasedAt": "1995-04-01",
    "parentSetCode": null
  },
  {
    "code": "5dn",
    "name": "Fifth Dawn",
    "setType": "expansion",
    "releasedAt": "2004-06-04",
    "parentSetCode": null
  },
  {
    "code": "5ed",
    "name": "Fifth Edition",
    "setType": "core",
    "releasedAt": "1997-03-24",
    "parentSetCode": null
  },
  {
    "code": "6ed",
    "name": "Classic Sixth Edition",
    "setType": "core",
    "releasedAt": "1999-04-21",
    "parentSetCode": null
  },
  {
    "code": "7ed",
    "name": "Seventh Edition",
    "setType": "core",
    "releasedAt": "2001-04-11",
    "parentSetCode": null
  },
  {
    "code": "8ed",
    "name": "Eighth Edition",
    "setType": "core",
    "releasedAt": "2003-07-28",
    "parentSetCode": null
  },
  {
    "code": "9ed",
    "name": "Ninth Edition",
    "setType": "core",
    "releasedAt": "2005-07-29",
    "parentSetCode": null
  },
  {
    "code": "a25",
    "name": "Masters 25",
    "setType": "masters",
    "releasedAt": "2018-03-16",
    "parentSetCode": null
  },
  {
    "code": "acr",
    "name": "Assassin's Creed",
    "setType": "draft_innovation",
    "releasedAt": "2024-07-05",
    "parentSetCode": null
  },
  {
    "code": "aer",
    "name": "Aether Revolt",
    "setType": "expansion",
    "releasedAt": "2017-01-20",
    "parentSetCode": null
  },
  {
    "code": "afc",
    "name": "Forgotten Realms Commander",
    "setType": "commander",
    "releasedAt": "2021-07-23",
    "parentSetCode": "afr"
  },
  {
    "code": "afr",
    "name": "Adventures in the Forgotten Realms",
    "setType": "expansion",
    "releasedAt": "2021-07-23",
    "parentSetCode": null
  },
  {
    "code": "akh",
    "name": "Amonkhet",
    "setType": "expansion",
    "releasedAt": "2017-04-28",
    "parentSetCode": null
  },
  {
    "code": "ala",
    "name": "Shards of Alara",
    "setType": "expansion",
    "releasedAt": "2008-10-03",
    "parentSetCode": null
  },
  {
    "code": "all",
    "name": "Alliances",
    "setType": "expansion",
    "releasedAt": "1996-06-10",
    "parentSetCode": null
  },
  {
    "code": "apc",
    "name": "Apocalypse",
    "setType": "expansion",
    "releasedAt": "2001-06-04",
    "parentSetCode": null
  },
  {
    "code": "arb",
    "name": "Alara Reborn",
    "setType": "expansion",
    "releasedAt": "2009-04-30",
    "parentSetCode": null
  },
  {
    "code": "arc",
    "name": "Archenemy",
    "setType": "archenemy",
    "releasedAt": "2010-06-18",
    "parentSetCode": null
  },
  {
    "code": "arn",
    "name": "Arabian Nights",
    "setType": "expansion",
    "releasedAt": "1993-12-17",
    "parentSetCode": null
  },
  {
    "code": "ath",
    "name": "Anthologies",
    "setType": "box",
    "releasedAt": "1998-11-01",
    "parentSetCode": null
  },
  {
    "code": "atq",
    "name": "Antiquities",
    "setType": "expansion",
    "releasedAt": "1994-03-04",
    "parentSetCode": null
  },
  {
    "code": "avr",
    "name": "Avacyn Restored",
    "setType": "expansion",
    "releasedAt": "2012-05-04",
    "parentSetCode": null
  },
  {
    "code": "bbd",
    "name": "Battlebond",
    "setType": "draft_innovation",
    "releasedAt": "2018-06-08",
    "parentSetCode": null
  },
  {
    "code": "bchr",
    "name": "Chronicles Foreign Black Border",
    "setType": "masters",
    "releasedAt": "1995-07-01",
    "parentSetCode": "chr"
  },
  {
    "code": "bfz",
    "name": "Battle for Zendikar",
    "setType": "expansion",
    "releasedAt": "2015-10-02",
    "parentSetCode": null
  },
  {
    "code": "big",
    "name": "The Big Score",
    "setType": "expansion",
    "releasedAt": "2024-04-19",
    "parentSetCode": "otj"
  },
  {
    "code": "blb",
    "name": "Bloomburrow",
    "setType": "expansion",
    "releasedAt": "2024-08-02",
    "parentSetCode": null
  },
  {
    "code": "blc",
    "name": "Bloomburrow Commander",
    "setType": "commander",
    "releasedAt": "2024-08-02",
    "parentSetCode": "blb"
  },
  {
    "code": "bng",
    "name": "Born of the Gods",
    "setType": "expansion",
    "releasedAt": "2014-02-07",
    "parentSetCode": null
  },
  {
    "code": "bok",
    "name": "Betrayers of Kamigawa",
    "setType": "expansion",
    "releasedAt": "2005-02-04",
    "parentSetCode": null
  },
  {
    "code": "bot",
    "name": "Transformers",
    "setType": "eternal",
    "releasedAt": "2022-11-18",
    "parentSetCode": "bro"
  },
  {
    "code": "brb",
    "name": "Battle Royale Box Set",
    "setType": "box",
    "releasedAt": "1999-11-12",
    "parentSetCode": null
  },
  {
    "code": "brc",
    "name": "The Brothers' War Commander",
    "setType": "commander",
    "releasedAt": "2022-11-18",
    "parentSetCode": "bro"
  },
  {
    "code": "bro",
    "name": "The Brothers' War",
    "setType": "expansion",
    "releasedAt": "2022-11-18",
    "parentSetCode": null
  },
  {
    "code": "brr",
    "name": "The Brothers' War Retro Artifacts",
    "setType": "masterpiece",
    "releasedAt": "2022-11-18",
    "parentSetCode": "bro"
  },
  {
    "code": "btd",
    "name": "Beatdown Box Set",
    "setType": "box",
    "releasedAt": "2000-10-01",
    "parentSetCode": null
  },
  {
    "code": "c13",
    "name": "Commander 2013",
    "setType": "commander",
    "releasedAt": "2013-11-01",
    "parentSetCode": null
  },
  {
    "code": "c14",
    "name": "Commander 2014",
    "setType": "commander",
    "releasedAt": "2014-11-07",
    "parentSetCode": null
  },
  {
    "code": "c15",
    "name": "Commander 2015",
    "setType": "commander",
    "releasedAt": "2015-11-13",
    "parentSetCode": null
  },
  {
    "code": "c16",
    "name": "Commander 2016",
    "setType": "commander",
    "releasedAt": "2016-11-11",
    "parentSetCode": null
  },
  {
    "code": "c17",
    "name": "Commander 2017",
    "setType": "commander",
    "releasedAt": "2017-08-25",
    "parentSetCode": null
  },
  {
    "code": "c18",
    "name": "Commander 2018",
    "setType": "commander",
    "releasedAt": "2018-08-10",
    "parentSetCode": null
  },
  {
    "code": "c19",
    "name": "Commander 2019",
    "setType": "commander",
    "releasedAt": "2019-08-23",
    "parentSetCode": null
  },
  {
    "code": "c20",
    "name": "Commander 2020",
    "setType": "commander",
    "releasedAt": "2020-04-17",
    "parentSetCode": null
  },
  {
    "code": "c21",
    "name": "Commander 2021",
    "setType": "commander",
    "releasedAt": "2021-04-23",
    "parentSetCode": null
  },
  {
    "code": "cc1",
    "name": "Commander Collection: Green",
    "setType": "arsenal",
    "releasedAt": "2020-12-04",
    "parentSetCode": null
  },
  {
    "code": "cc2",
    "name": "Commander Collection: Black",
    "setType": "arsenal",
    "releasedAt": "2022-01-28",
    "parentSetCode": null
  },
  {
    "code": "chk",
    "name": "Champions of Kamigawa",
    "setType": "expansion",
    "releasedAt": "2004-10-01",
    "parentSetCode": null
  },
  {
    "code": "chr",
    "name": "Chronicles",
    "setType": "masters",
    "releasedAt": "1995-07-01",
    "parentSetCode": null
  },
  {
    "code": "clb",
    "name": "Commander Legends: Battle for Baldur's Gate",
    "setType": "draft_innovation",
    "releasedAt": "2022-06-10",
    "parentSetCode": null
  },
  {
    "code": "clu",
    "name": "Ravnica: Clue Edition",
    "setType": "draft_innovation",
    "releasedAt": "2024-02-23",
    "parentSetCode": "mkm"
  },
  {
    "code": "cm1",
    "name": "Commander's Arsenal",
    "setType": "arsenal",
    "releasedAt": "2012-11-02",
    "parentSetCode": null
  },
  {
    "code": "cm2",
    "name": "Commander Anthology Volume II",
    "setType": "commander",
    "releasedAt": "2018-06-08",
    "parentSetCode": null
  },
  {
    "code": "cma",
    "name": "Commander Anthology",
    "setType": "commander",
    "releasedAt": "2017-06-09",
    "parentSetCode": null
  },
  {
    "code": "cmb1",
    "name": "Mystery Booster Playtest Cards 2019",
    "setType": "funny",
    "releasedAt": "2019-11-07",
    "parentSetCode": null
  },
  {
    "code": "cmb2",
    "name": "Mystery Booster Playtest Cards 2021",
    "setType": "funny",
    "releasedAt": "2021-08-20",
    "parentSetCode": null
  },
  {
    "code": "cmd",
    "name": "Commander 2011",
    "setType": "commander",
    "releasedAt": "2011-06-17",
    "parentSetCode": null
  },
  {
    "code": "cmm",
    "name": "Commander Masters",
    "setType": "masters",
    "releasedAt": "2023-08-04",
    "parentSetCode": null
  },
  {
    "code": "cmr",
    "name": "Commander Legends",
    "setType": "draft_innovation",
    "releasedAt": "2020-11-20",
    "parentSetCode": null
  },
  {
    "code": "cn2",
    "name": "Conspiracy: Take the Crown",
    "setType": "draft_innovation",
    "releasedAt": "2016-08-26",
    "parentSetCode": null
  },
  {
    "code": "cns",
    "name": "Conspiracy",
    "setType": "draft_innovation",
    "releasedAt": "2014-06-06",
    "parentSetCode": null
  },
  {
    "code": "con",
    "name": "Conflux",
    "setType": "expansion",
    "releasedAt": "2009-02-06",
    "parentSetCode": null
  },
  {
    "code": "cp1",
    "name": "Magic 2015 Clash Pack",
    "setType": "starter",
    "releasedAt": "2014-07-18",
    "parentSetCode": "m15"
  },
  {
    "code": "cp2",
    "name": "Fate Reforged Clash Pack",
    "setType": "starter",
    "releasedAt": "2015-01-23",
    "parentSetCode": "frf"
  },
  {
    "code": "cp3",
    "name": "Magic Origins Clash Pack",
    "setType": "starter",
    "releasedAt": "2015-07-17",
    "parentSetCode": "ori"
  },
  {
    "code": "csp",
    "name": "Coldsnap",
    "setType": "expansion",
    "releasedAt": "2006-07-21",
    "parentSetCode": null
  },
  {
    "code": "cst",
    "name": "Coldsnap Theme Decks",
    "setType": "box",
    "releasedAt": "2006-07-21",
    "parentSetCode": "csp"
  },
  {
    "code": "dbl",
    "name": "Innistrad: Double Feature",
    "setType": "draft_innovation",
    "releasedAt": "2022-01-28",
    "parentSetCode": null
  },
  {
    "code": "dci",
    "name": "DCI Promos",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "dd1",
    "name": "Duel Decks: Elves vs. Goblins",
    "setType": "duel_deck",
    "releasedAt": "2007-11-16",
    "parentSetCode": null
  },
  {
    "code": "dd2",
    "name": "Duel Decks: Jace vs. Chandra",
    "setType": "duel_deck",
    "releasedAt": "2008-11-07",
    "parentSetCode": null
  },
  {
    "code": "ddc",
    "name": "Duel Decks: Divine vs. Demonic",
    "setType": "duel_deck",
    "releasedAt": "2009-04-10",
    "parentSetCode": null
  },
  {
    "code": "ddd",
    "name": "Duel Decks: Garruk vs. Liliana",
    "setType": "duel_deck",
    "releasedAt": "2009-10-30",
    "parentSetCode": null
  },
  {
    "code": "dde",
    "name": "Duel Decks: Phyrexia vs. the Coalition",
    "setType": "duel_deck",
    "releasedAt": "2010-03-19",
    "parentSetCode": null
  },
  {
    "code": "ddf",
    "name": "Duel Decks: Elspeth vs. Tezzeret",
    "setType": "duel_deck",
    "releasedAt": "2010-09-03",
    "parentSetCode": null
  },
  {
    "code": "ddg",
    "name": "Duel Decks: Knights vs. Dragons",
    "setType": "duel_deck",
    "releasedAt": "2011-04-01",
    "parentSetCode": null
  },
  {
    "code": "ddh",
    "name": "Duel Decks: Ajani vs. Nicol Bolas",
    "setType": "duel_deck",
    "releasedAt": "2011-09-02",
    "parentSetCode": null
  },
  {
    "code": "ddi",
    "name": "Duel Decks: Venser vs. Koth",
    "setType": "duel_deck",
    "releasedAt": "2012-03-30",
    "parentSetCode": null
  },
  {
    "code": "ddj",
    "name": "Duel Decks: Izzet vs. Golgari",
    "setType": "duel_deck",
    "releasedAt": "2012-09-07",
    "parentSetCode": null
  },
  {
    "code": "ddk",
    "name": "Duel Decks: Sorin vs. Tibalt",
    "setType": "duel_deck",
    "releasedAt": "2013-03-15",
    "parentSetCode": null
  },
  {
    "code": "ddl",
    "name": "Duel Decks: Heroes vs. Monsters",
    "setType": "duel_deck",
    "releasedAt": "2013-09-06",
    "parentSetCode": null
  },
  {
    "code": "ddm",
    "name": "Duel Decks: Jace vs. Vraska",
    "setType": "duel_deck",
    "releasedAt": "2014-03-14",
    "parentSetCode": null
  },
  {
    "code": "ddn",
    "name": "Duel Decks: Speed vs. Cunning",
    "setType": "duel_deck",
    "releasedAt": "2014-09-05",
    "parentSetCode": null
  },
  {
    "code": "ddo",
    "name": "Duel Decks: Elspeth vs. Kiora",
    "setType": "duel_deck",
    "releasedAt": "2015-02-27",
    "parentSetCode": null
  },
  {
    "code": "ddp",
    "name": "Duel Decks: Zendikar vs. Eldrazi",
    "setType": "duel_deck",
    "releasedAt": "2015-08-28",
    "parentSetCode": null
  },
  {
    "code": "ddq",
    "name": "Duel Decks: Blessed vs. Cursed",
    "setType": "duel_deck",
    "releasedAt": "2016-02-26",
    "parentSetCode": null
  },
  {
    "code": "ddr",
    "name": "Duel Decks: Nissa vs. Ob Nixilis",
    "setType": "duel_deck",
    "releasedAt": "2016-09-02",
    "parentSetCode": null
  },
  {
    "code": "dds",
    "name": "Duel Decks: Mind vs. Might",
    "setType": "duel_deck",
    "releasedAt": "2017-03-31",
    "parentSetCode": null
  },
  {
    "code": "ddt",
    "name": "Duel Decks: Merfolk vs. Goblins",
    "setType": "duel_deck",
    "releasedAt": "2017-10-24",
    "parentSetCode": null
  },
  {
    "code": "ddu",
    "name": "Duel Decks: Elves vs. Inventors",
    "setType": "duel_deck",
    "releasedAt": "2018-04-06",
    "parentSetCode": null
  },
  {
    "code": "dft",
    "name": "Aetherdrift",
    "setType": "expansion",
    "releasedAt": "2025-02-14",
    "parentSetCode": null
  },
  {
    "code": "dgm",
    "name": "Dragon's Maze",
    "setType": "expansion",
    "releasedAt": "2013-05-03",
    "parentSetCode": null
  },
  {
    "code": "dis",
    "name": "Dissension",
    "setType": "expansion",
    "releasedAt": "2006-05-05",
    "parentSetCode": null
  },
  {
    "code": "dka",
    "name": "Dark Ascension",
    "setType": "expansion",
    "releasedAt": "2012-02-03",
    "parentSetCode": null
  },
  {
    "code": "dkm",
    "name": "Deckmasters",
    "setType": "box",
    "releasedAt": "2001-12-01",
    "parentSetCode": null
  },
  {
    "code": "dmc",
    "name": "Dominaria United Commander",
    "setType": "commander",
    "releasedAt": "2022-09-09",
    "parentSetCode": "dmu"
  },
  {
    "code": "dmr",
    "name": "Dominaria Remastered",
    "setType": "masters",
    "releasedAt": "2023-01-13",
    "parentSetCode": null
  },
  {
    "code": "dmu",
    "name": "Dominaria United",
    "setType": "expansion",
    "releasedAt": "2022-09-09",
    "parentSetCode": null
  },
  {
    "code": "dom",
    "name": "Dominaria",
    "setType": "expansion",
    "releasedAt": "2018-04-27",
    "parentSetCode": null
  },
  {
    "code": "dpa",
    "name": "Duels of the Planeswalkers",
    "setType": "box",
    "releasedAt": "2010-06-04",
    "parentSetCode": null
  },
  {
    "code": "drb",
    "name": "From the Vault: Dragons",
    "setType": "from_the_vault",
    "releasedAt": "2008-08-29",
    "parentSetCode": null
  },
  {
    "code": "drc",
    "name": "Aetherdrift Commander",
    "setType": "commander",
    "releasedAt": "2025-02-14",
    "parentSetCode": "dft"
  },
  {
    "code": "drk",
    "name": "The Dark",
    "setType": "expansion",
    "releasedAt": "1994-08-01",
    "parentSetCode": null
  },
  {
    "code": "dsc",
    "name": "Duskmourn: House of Horror Commander",
    "setType": "commander",
    "releasedAt": "2024-09-27",
    "parentSetCode": "dsk"
  },
  {
    "code": "dsk",
    "name": "Duskmourn: House of Horror",
    "setType": "expansion",
    "releasedAt": "2024-09-27",
    "parentSetCode": null
  },
  {
    "code": "dst",
    "name": "Darksteel",
    "setType": "expansion",
    "releasedAt": "2004-02-06",
    "parentSetCode": null
  },
  {
    "code": "dtk",
    "name": "Dragons of Tarkir",
    "setType": "expansion",
    "releasedAt": "2015-03-27",
    "parentSetCode": null
  },
  {
    "code": "dvd",
    "name": "Duel Decks Anthology: Divine vs. Demonic",
    "setType": "duel_deck",
    "releasedAt": "2014-12-05",
    "parentSetCode": null
  },
  {
    "code": "e01",
    "name": "Archenemy: Nicol Bolas",
    "setType": "archenemy",
    "releasedAt": "2017-06-16",
    "parentSetCode": null
  },
  {
    "code": "e02",
    "name": "Explorers of Ixalan",
    "setType": "box",
    "releasedAt": "2017-11-24",
    "parentSetCode": null
  },
  {
    "code": "ecc",
    "name": "Lorwyn Eclipsed Commander",
    "setType": "commander",
    "releasedAt": "2026-01-23",
    "parentSetCode": "ecl"
  },
  {
    "code": "ecl",
    "name": "Lorwyn Eclipsed",
    "setType": "expansion",
    "releasedAt": "2026-01-23",
    "parentSetCode": null
  },
  {
    "code": "eld",
    "name": "Throne of Eldraine",
    "setType": "expansion",
    "releasedAt": "2019-10-04",
    "parentSetCode": null
  },
  {
    "code": "ema",
    "name": "Eternal Masters",
    "setType": "masters",
    "releasedAt": "2016-06-10",
    "parentSetCode": null
  },
  {
    "code": "emn",
    "name": "Eldritch Moon",
    "setType": "expansion",
    "releasedAt": "2016-07-22",
    "parentSetCode": null
  },
  {
    "code": "eoc",
    "name": "Edge of Eternities Commander",
    "setType": "commander",
    "releasedAt": "2025-08-01",
    "parentSetCode": "eoe"
  },
  {
    "code": "eoe",
    "name": "Edge of Eternities",
    "setType": "expansion",
    "releasedAt": "2025-08-01",
    "parentSetCode": null
  },
  {
    "code": "eos",
    "name": "Edge of Eternities: Stellar Sights",
    "setType": "masterpiece",
    "releasedAt": "2025-08-01",
    "parentSetCode": "eoe"
  },
  {
    "code": "eve",
    "name": "Eventide",
    "setType": "expansion",
    "releasedAt": "2008-07-25",
    "parentSetCode": null
  },
  {
    "code": "evg",
    "name": "Duel Decks Anthology: Elves vs. Goblins",
    "setType": "duel_deck",
    "releasedAt": "2014-12-05",
    "parentSetCode": null
  },
  {
    "code": "exo",
    "name": "Exodus",
    "setType": "expansion",
    "releasedAt": "1998-06-15",
    "parentSetCode": null
  },
  {
    "code": "exp",
    "name": "Zendikar Expeditions",
    "setType": "masterpiece",
    "releasedAt": "2015-10-02",
    "parentSetCode": "bfz"
  },
  {
    "code": "f01",
    "name": "Friday Night Magic 2001",
    "setType": "promo",
    "releasedAt": "2001-01-01",
    "parentSetCode": null
  },
  {
    "code": "f02",
    "name": "Friday Night Magic 2002",
    "setType": "promo",
    "releasedAt": "2002-01-01",
    "parentSetCode": null
  },
  {
    "code": "f03",
    "name": "Friday Night Magic 2003",
    "setType": "promo",
    "releasedAt": "2003-01-01",
    "parentSetCode": null
  },
  {
    "code": "f04",
    "name": "Friday Night Magic 2004",
    "setType": "promo",
    "releasedAt": "2004-01-01",
    "parentSetCode": null
  },
  {
    "code": "f05",
    "name": "Friday Night Magic 2005",
    "setType": "promo",
    "releasedAt": "2005-01-01",
    "parentSetCode": null
  },
  {
    "code": "f06",
    "name": "Friday Night Magic 2006",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "f07",
    "name": "Friday Night Magic 2007",
    "setType": "promo",
    "releasedAt": "2007-01-01",
    "parentSetCode": null
  },
  {
    "code": "f08",
    "name": "Friday Night Magic 2008",
    "setType": "promo",
    "releasedAt": "2008-01-01",
    "parentSetCode": null
  },
  {
    "code": "f09",
    "name": "Friday Night Magic 2009",
    "setType": "promo",
    "releasedAt": "2009-01-01",
    "parentSetCode": null
  },
  {
    "code": "f10",
    "name": "Friday Night Magic 2010",
    "setType": "promo",
    "releasedAt": "2010-01-01",
    "parentSetCode": null
  },
  {
    "code": "f11",
    "name": "Friday Night Magic 2011",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "f12",
    "name": "Friday Night Magic 2012",
    "setType": "promo",
    "releasedAt": "2012-01-01",
    "parentSetCode": null
  },
  {
    "code": "f13",
    "name": "Friday Night Magic 2013",
    "setType": "promo",
    "releasedAt": "2013-01-01",
    "parentSetCode": null
  },
  {
    "code": "f14",
    "name": "Friday Night Magic 2014",
    "setType": "promo",
    "releasedAt": "2014-01-01",
    "parentSetCode": null
  },
  {
    "code": "f15",
    "name": "Friday Night Magic 2015",
    "setType": "promo",
    "releasedAt": "2015-01-01",
    "parentSetCode": null
  },
  {
    "code": "f16",
    "name": "Friday Night Magic 2016",
    "setType": "promo",
    "releasedAt": "2016-01-01",
    "parentSetCode": null
  },
  {
    "code": "f17",
    "name": "Friday Night Magic 2017",
    "setType": "promo",
    "releasedAt": "2017-01-01",
    "parentSetCode": null
  },
  {
    "code": "f18",
    "name": "Friday Night Magic 2018",
    "setType": "promo",
    "releasedAt": "2017-12-27",
    "parentSetCode": null
  },
  {
    "code": "fbb",
    "name": "Foreign Black Border",
    "setType": "core",
    "releasedAt": "1994-04-11",
    "parentSetCode": "3ed"
  },
  {
    "code": "fca",
    "name": "Final Fantasy: Through the Ages",
    "setType": "masterpiece",
    "releasedAt": "2025-06-13",
    "parentSetCode": "fin"
  },
  {
    "code": "fdc",
    "name": "Foundations Commander",
    "setType": "commander",
    "releasedAt": "2024-11-15",
    "parentSetCode": "fdn"
  },
  {
    "code": "fdn",
    "name": "Foundations",
    "setType": "core",
    "releasedAt": "2024-11-15",
    "parentSetCode": null
  },
  {
    "code": "fem",
    "name": "Fallen Empires",
    "setType": "expansion",
    "releasedAt": "1994-11-01",
    "parentSetCode": null
  },
  {
    "code": "fic",
    "name": "Final Fantasy Commander",
    "setType": "commander",
    "releasedAt": "2025-06-13",
    "parentSetCode": "fin"
  },
  {
    "code": "fin",
    "name": "Final Fantasy",
    "setType": "expansion",
    "releasedAt": "2025-06-13",
    "parentSetCode": null
  },
  {
    "code": "fnm",
    "name": "Friday Night Magic 2000",
    "setType": "promo",
    "releasedAt": "2000-01-01",
    "parentSetCode": null
  },
  {
    "code": "fra",
    "name": "Reality Fracture",
    "setType": "expansion",
    "releasedAt": "2026-10-02",
    "parentSetCode": null
  },
  {
    "code": "frc",
    "name": "Reality Fracture Commander",
    "setType": "commander",
    "releasedAt": "2026-10-02",
    "parentSetCode": "fra"
  },
  {
    "code": "frf",
    "name": "Fate Reforged",
    "setType": "expansion",
    "releasedAt": "2015-01-23",
    "parentSetCode": null
  },
  {
    "code": "fut",
    "name": "Future Sight",
    "setType": "expansion",
    "releasedAt": "2007-05-04",
    "parentSetCode": null
  },
  {
    "code": "g00",
    "name": "Judge Gift Cards 2000",
    "setType": "promo",
    "releasedAt": "2000-01-01",
    "parentSetCode": null
  },
  {
    "code": "g01",
    "name": "Judge Gift Cards 2001",
    "setType": "promo",
    "releasedAt": "2001-01-01",
    "parentSetCode": null
  },
  {
    "code": "g02",
    "name": "Judge Gift Cards 2002",
    "setType": "promo",
    "releasedAt": "2002-01-01",
    "parentSetCode": null
  },
  {
    "code": "g03",
    "name": "Judge Gift Cards 2003",
    "setType": "promo",
    "releasedAt": "2003-01-01",
    "parentSetCode": null
  },
  {
    "code": "g04",
    "name": "Judge Gift Cards 2004",
    "setType": "promo",
    "releasedAt": "2004-01-01",
    "parentSetCode": null
  },
  {
    "code": "g05",
    "name": "Judge Gift Cards 2005",
    "setType": "promo",
    "releasedAt": "2005-01-01",
    "parentSetCode": null
  },
  {
    "code": "g06",
    "name": "Judge Gift Cards 2006",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "g07",
    "name": "Judge Gift Cards 2007",
    "setType": "promo",
    "releasedAt": "2007-01-01",
    "parentSetCode": null
  },
  {
    "code": "g08",
    "name": "Judge Gift Cards 2008",
    "setType": "promo",
    "releasedAt": "2008-01-01",
    "parentSetCode": null
  },
  {
    "code": "g09",
    "name": "Judge Gift Cards 2009",
    "setType": "promo",
    "releasedAt": "2009-01-01",
    "parentSetCode": null
  },
  {
    "code": "g10",
    "name": "Judge Gift Cards 2010",
    "setType": "promo",
    "releasedAt": "2010-01-01",
    "parentSetCode": null
  },
  {
    "code": "g11",
    "name": "Judge Gift Cards 2011",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "g17",
    "name": "2017 Gift Pack",
    "setType": "box",
    "releasedAt": "2017-10-20",
    "parentSetCode": null
  },
  {
    "code": "g18",
    "name": "M19 Gift Pack",
    "setType": "box",
    "releasedAt": "2018-11-16",
    "parentSetCode": "m19"
  },
  {
    "code": "g99",
    "name": "Judge Gift Cards 1999",
    "setType": "promo",
    "releasedAt": "1999-01-01",
    "parentSetCode": null
  },
  {
    "code": "gdy",
    "name": "Game Day Promos",
    "setType": "promo",
    "releasedAt": "2022-04-08",
    "parentSetCode": null
  },
  {
    "code": "gk1",
    "name": "GRN Guild Kit",
    "setType": "box",
    "releasedAt": "2018-11-02",
    "parentSetCode": null
  },
  {
    "code": "gk2",
    "name": "RNA Guild Kit",
    "setType": "box",
    "releasedAt": "2019-02-15",
    "parentSetCode": null
  },
  {
    "code": "gn2",
    "name": "Game Night 2019",
    "setType": "box",
    "releasedAt": "2019-11-15",
    "parentSetCode": null
  },
  {
    "code": "gn3",
    "name": "Game Night: Free-for-All",
    "setType": "box",
    "releasedAt": "2022-10-14",
    "parentSetCode": null
  },
  {
    "code": "gnt",
    "name": "Game Night",
    "setType": "box",
    "releasedAt": "2018-11-16",
    "parentSetCode": null
  },
  {
    "code": "gpt",
    "name": "Guildpact",
    "setType": "expansion",
    "releasedAt": "2006-02-03",
    "parentSetCode": null
  },
  {
    "code": "grn",
    "name": "Guilds of Ravnica",
    "setType": "expansion",
    "releasedAt": "2018-10-05",
    "parentSetCode": null
  },
  {
    "code": "gs1",
    "name": "Global Series Jiang Yanggu & Mu Yanling",
    "setType": "duel_deck",
    "releasedAt": "2018-06-22",
    "parentSetCode": null
  },
  {
    "code": "gtc",
    "name": "Gatecrash",
    "setType": "expansion",
    "releasedAt": "2013-02-01",
    "parentSetCode": null
  },
  {
    "code": "gvl",
    "name": "Duel Decks Anthology: Garruk vs. Liliana",
    "setType": "duel_deck",
    "releasedAt": "2014-12-05",
    "parentSetCode": null
  },
  {
    "code": "h09",
    "name": "Premium Deck Series: Slivers",
    "setType": "premium_deck",
    "releasedAt": "2009-11-20",
    "parentSetCode": null
  },
  {
    "code": "h17",
    "name": "HasCon 2017",
    "setType": "funny",
    "releasedAt": "2017-09-20",
    "parentSetCode": null
  },
  {
    "code": "h1r",
    "name": "Modern Horizons 1 Timeshifts",
    "setType": "draft_innovation",
    "releasedAt": "2021-06-18",
    "parentSetCode": "mh2"
  },
  {
    "code": "h2r",
    "name": "Modern Horizons 2 Timeshifts",
    "setType": "draft_innovation",
    "releasedAt": "2024-06-14",
    "parentSetCode": "mh3"
  },
  {
    "code": "hho",
    "name": "Happy Holidays",
    "setType": "funny",
    "releasedAt": "2006-12-31",
    "parentSetCode": null
  },
  {
    "code": "hml",
    "name": "Homelands",
    "setType": "expansion",
    "releasedAt": "1995-10-01",
    "parentSetCode": null
  },
  {
    "code": "hob",
    "name": "The Hobbit",
    "setType": "expansion",
    "releasedAt": "2026-08-14",
    "parentSetCode": null
  },
  {
    "code": "hoc",
    "name": "The Hobbit Eternal",
    "setType": "eternal",
    "releasedAt": "2026-08-14",
    "parentSetCode": "hob"
  },
  {
    "code": "hop",
    "name": "Planechase",
    "setType": "planechase",
    "releasedAt": "2009-09-04",
    "parentSetCode": null
  },
  {
    "code": "hou",
    "name": "Hour of Devastation",
    "setType": "expansion",
    "releasedAt": "2017-07-14",
    "parentSetCode": null
  },
  {
    "code": "ice",
    "name": "Ice Age",
    "setType": "expansion",
    "releasedAt": "1995-06-03",
    "parentSetCode": null
  },
  {
    "code": "iko",
    "name": "Ikoria: Lair of Behemoths",
    "setType": "expansion",
    "releasedAt": "2020-04-24",
    "parentSetCode": null
  },
  {
    "code": "ima",
    "name": "Iconic Masters",
    "setType": "masters",
    "releasedAt": "2017-11-17",
    "parentSetCode": null
  },
  {
    "code": "inr",
    "name": "Innistrad Remastered",
    "setType": "masters",
    "releasedAt": "2025-01-24",
    "parentSetCode": null
  },
  {
    "code": "inv",
    "name": "Invasion",
    "setType": "expansion",
    "releasedAt": "2000-10-02",
    "parentSetCode": null
  },
  {
    "code": "isd",
    "name": "Innistrad",
    "setType": "expansion",
    "releasedAt": "2011-09-30",
    "parentSetCode": null
  },
  {
    "code": "itp",
    "name": "Introductory Two-Player Set",
    "setType": "starter",
    "releasedAt": "1996-12-31",
    "parentSetCode": null
  },
  {
    "code": "j12",
    "name": "Judge Gift Cards 2012",
    "setType": "promo",
    "releasedAt": "2012-01-01",
    "parentSetCode": null
  },
  {
    "code": "j13",
    "name": "Judge Gift Cards 2013",
    "setType": "promo",
    "releasedAt": "2013-01-01",
    "parentSetCode": null
  },
  {
    "code": "j14",
    "name": "Judge Gift Cards 2014",
    "setType": "promo",
    "releasedAt": "2014-01-01",
    "parentSetCode": null
  },
  {
    "code": "j15",
    "name": "Judge Gift Cards 2015",
    "setType": "promo",
    "releasedAt": "2015-01-01",
    "parentSetCode": null
  },
  {
    "code": "j16",
    "name": "Judge Gift Cards 2016",
    "setType": "promo",
    "releasedAt": "2016-01-01",
    "parentSetCode": null
  },
  {
    "code": "j17",
    "name": "Judge Gift Cards 2017",
    "setType": "promo",
    "releasedAt": "2017-01-01",
    "parentSetCode": null
  },
  {
    "code": "j18",
    "name": "Judge Gift Cards 2018",
    "setType": "promo",
    "releasedAt": "2018-01-01",
    "parentSetCode": null
  },
  {
    "code": "j19",
    "name": "Judge Gift Cards 2019",
    "setType": "promo",
    "releasedAt": "2019-04-10",
    "parentSetCode": null
  },
  {
    "code": "j20",
    "name": "Judge Gift Cards 2020",
    "setType": "promo",
    "releasedAt": "2020-01-01",
    "parentSetCode": null
  },
  {
    "code": "j22",
    "name": "Jumpstart 2022",
    "setType": "draft_innovation",
    "releasedAt": "2022-12-02",
    "parentSetCode": null
  },
  {
    "code": "j25",
    "name": "Foundations Jumpstart",
    "setType": "draft_innovation",
    "releasedAt": "2024-11-15",
    "parentSetCode": "fdn"
  },
  {
    "code": "jgp",
    "name": "Judge Gift Cards 1998",
    "setType": "promo",
    "releasedAt": "1998-01-01",
    "parentSetCode": null
  },
  {
    "code": "jmp",
    "name": "Jumpstart",
    "setType": "draft_innovation",
    "releasedAt": "2020-07-17",
    "parentSetCode": null
  },
  {
    "code": "jou",
    "name": "Journey into Nyx",
    "setType": "expansion",
    "releasedAt": "2014-05-02",
    "parentSetCode": null
  },
  {
    "code": "jp1",
    "name": "Hobby Japan Promos",
    "setType": "promo",
    "releasedAt": "2002-07-01",
    "parentSetCode": null
  },
  {
    "code": "jud",
    "name": "Judgment",
    "setType": "expansion",
    "releasedAt": "2002-05-27",
    "parentSetCode": null
  },
  {
    "code": "jvc",
    "name": "Duel Decks Anthology: Jace vs. Chandra",
    "setType": "duel_deck",
    "releasedAt": "2014-12-05",
    "parentSetCode": null
  },
  {
    "code": "khc",
    "name": "Kaldheim Commander",
    "setType": "commander",
    "releasedAt": "2021-02-05",
    "parentSetCode": "khm"
  },
  {
    "code": "khm",
    "name": "Kaldheim",
    "setType": "expansion",
    "releasedAt": "2021-02-05",
    "parentSetCode": null
  },
  {
    "code": "kld",
    "name": "Kaladesh",
    "setType": "expansion",
    "releasedAt": "2016-09-30",
    "parentSetCode": null
  },
  {
    "code": "ktk",
    "name": "Khans of Tarkir",
    "setType": "expansion",
    "releasedAt": "2014-09-26",
    "parentSetCode": null
  },
  {
    "code": "lcc",
    "name": "The Lost Caverns of Ixalan Commander",
    "setType": "commander",
    "releasedAt": "2023-11-17",
    "parentSetCode": "lci"
  },
  {
    "code": "lci",
    "name": "The Lost Caverns of Ixalan",
    "setType": "expansion",
    "releasedAt": "2023-11-17",
    "parentSetCode": null
  },
  {
    "code": "lea",
    "name": "Limited Edition Alpha",
    "setType": "core",
    "releasedAt": "1993-08-05",
    "parentSetCode": null
  },
  {
    "code": "leb",
    "name": "Limited Edition Beta",
    "setType": "core",
    "releasedAt": "1993-10-04",
    "parentSetCode": null
  },
  {
    "code": "leg",
    "name": "Legends",
    "setType": "expansion",
    "releasedAt": "1994-06-01",
    "parentSetCode": null
  },
  {
    "code": "lgn",
    "name": "Legions",
    "setType": "expansion",
    "releasedAt": "2003-02-03",
    "parentSetCode": null
  },
  {
    "code": "lmar",
    "name": "Marvel Legends Series Inserts",
    "setType": "promo",
    "releasedAt": "2025-09-30",
    "parentSetCode": "mar"
  },
  {
    "code": "lrw",
    "name": "Lorwyn",
    "setType": "expansion",
    "releasedAt": "2007-10-12",
    "parentSetCode": null
  },
  {
    "code": "ltc",
    "name": "Tales of Middle-earth Commander",
    "setType": "commander",
    "releasedAt": "2023-06-23",
    "parentSetCode": "ltr"
  },
  {
    "code": "ltr",
    "name": "The Lord of the Rings: Tales of Middle-earth",
    "setType": "draft_innovation",
    "releasedAt": "2023-06-23",
    "parentSetCode": null
  },
  {
    "code": "m10",
    "name": "Magic 2010",
    "setType": "core",
    "releasedAt": "2009-07-17",
    "parentSetCode": null
  },
  {
    "code": "m11",
    "name": "Magic 2011",
    "setType": "core",
    "releasedAt": "2010-07-16",
    "parentSetCode": null
  },
  {
    "code": "m12",
    "name": "Magic 2012",
    "setType": "core",
    "releasedAt": "2011-07-15",
    "parentSetCode": null
  },
  {
    "code": "m13",
    "name": "Magic 2013",
    "setType": "core",
    "releasedAt": "2012-07-13",
    "parentSetCode": null
  },
  {
    "code": "m14",
    "name": "Magic 2014",
    "setType": "core",
    "releasedAt": "2013-07-19",
    "parentSetCode": null
  },
  {
    "code": "m15",
    "name": "Magic 2015",
    "setType": "core",
    "releasedAt": "2014-07-18",
    "parentSetCode": null
  },
  {
    "code": "m19",
    "name": "Core Set 2019",
    "setType": "core",
    "releasedAt": "2018-07-13",
    "parentSetCode": null
  },
  {
    "code": "m20",
    "name": "Core Set 2020",
    "setType": "core",
    "releasedAt": "2019-07-12",
    "parentSetCode": null
  },
  {
    "code": "m21",
    "name": "Core Set 2021",
    "setType": "core",
    "releasedAt": "2020-07-03",
    "parentSetCode": null
  },
  {
    "code": "m3c",
    "name": "Modern Horizons 3 Commander",
    "setType": "commander",
    "releasedAt": "2024-06-14",
    "parentSetCode": "mh3"
  },
  {
    "code": "mar",
    "name": "Marvel Universe",
    "setType": "masterpiece",
    "releasedAt": "2025-09-26",
    "parentSetCode": null
  },
  {
    "code": "mat",
    "name": "March of the Machine: The Aftermath",
    "setType": "expansion",
    "releasedAt": "2023-05-12",
    "parentSetCode": null
  },
  {
    "code": "mb2",
    "name": "Mystery Booster 2",
    "setType": "masters",
    "releasedAt": "2024-08-02",
    "parentSetCode": null
  },
  {
    "code": "mbc",
    "name": "Mystery Booster Commander Edition",
    "setType": "draft_innovation",
    "releasedAt": "2026-11-09",
    "parentSetCode": null
  },
  {
    "code": "mbs",
    "name": "Mirrodin Besieged",
    "setType": "expansion",
    "releasedAt": "2011-02-04",
    "parentSetCode": null
  },
  {
    "code": "md1",
    "name": "Modern Event Deck 2014",
    "setType": "box",
    "releasedAt": "2014-05-30",
    "parentSetCode": null
  },
  {
    "code": "med",
    "name": "Mythic Edition",
    "setType": "masterpiece",
    "releasedAt": "2018-10-05",
    "parentSetCode": null
  },
  {
    "code": "mgb",
    "name": "Multiverse Gift Box",
    "setType": "box",
    "releasedAt": "1996-11-01",
    "parentSetCode": "vis"
  },
  {
    "code": "mh1",
    "name": "Modern Horizons",
    "setType": "draft_innovation",
    "releasedAt": "2019-06-14",
    "parentSetCode": null
  },
  {
    "code": "mh2",
    "name": "Modern Horizons 2",
    "setType": "draft_innovation",
    "releasedAt": "2021-06-18",
    "parentSetCode": null
  },
  {
    "code": "mh3",
    "name": "Modern Horizons 3",
    "setType": "draft_innovation",
    "releasedAt": "2024-06-14",
    "parentSetCode": null
  },
  {
    "code": "mic",
    "name": "Midnight Hunt Commander",
    "setType": "commander",
    "releasedAt": "2021-09-24",
    "parentSetCode": "mid"
  },
  {
    "code": "mid",
    "name": "Innistrad: Midnight Hunt",
    "setType": "expansion",
    "releasedAt": "2021-09-24",
    "parentSetCode": null
  },
  {
    "code": "mir",
    "name": "Mirage",
    "setType": "expansion",
    "releasedAt": "1996-10-08",
    "parentSetCode": null
  },
  {
    "code": "mkc",
    "name": "Murders at Karlov Manor Commander",
    "setType": "commander",
    "releasedAt": "2024-02-09",
    "parentSetCode": "mkm"
  },
  {
    "code": "mkm",
    "name": "Murders at Karlov Manor",
    "setType": "expansion",
    "releasedAt": "2024-02-09",
    "parentSetCode": null
  },
  {
    "code": "mm2",
    "name": "Modern Masters 2015",
    "setType": "masters",
    "releasedAt": "2015-05-22",
    "parentSetCode": null
  },
  {
    "code": "mm3",
    "name": "Modern Masters 2017",
    "setType": "masters",
    "releasedAt": "2017-03-17",
    "parentSetCode": null
  },
  {
    "code": "mma",
    "name": "Modern Masters",
    "setType": "masters",
    "releasedAt": "2013-06-07",
    "parentSetCode": null
  },
  {
    "code": "mmq",
    "name": "Mercadian Masques",
    "setType": "expansion",
    "releasedAt": "1999-10-04",
    "parentSetCode": null
  },
  {
    "code": "moc",
    "name": "March of the Machine Commander",
    "setType": "commander",
    "releasedAt": "2023-04-21",
    "parentSetCode": "mom"
  },
  {
    "code": "mom",
    "name": "March of the Machine",
    "setType": "expansion",
    "releasedAt": "2023-04-21",
    "parentSetCode": null
  },
  {
    "code": "mor",
    "name": "Morningtide",
    "setType": "expansion",
    "releasedAt": "2008-02-01",
    "parentSetCode": null
  },
  {
    "code": "mp2",
    "name": "Amonkhet Invocations",
    "setType": "masterpiece",
    "releasedAt": "2017-04-28",
    "parentSetCode": "akh"
  },
  {
    "code": "mpr",
    "name": "Magic Player Rewards 2001",
    "setType": "promo",
    "releasedAt": "2001-01-01",
    "parentSetCode": null
  },
  {
    "code": "mps",
    "name": "Kaladesh Inventions",
    "setType": "masterpiece",
    "releasedAt": "2016-09-30",
    "parentSetCode": "kld"
  },
  {
    "code": "mrd",
    "name": "Mirrodin",
    "setType": "expansion",
    "releasedAt": "2003-10-02",
    "parentSetCode": null
  },
  {
    "code": "msc",
    "name": "Marvel Super Heroes Commander",
    "setType": "commander",
    "releasedAt": "2026-06-26",
    "parentSetCode": "msh"
  },
  {
    "code": "msh",
    "name": "Marvel Super Heroes",
    "setType": "expansion",
    "releasedAt": "2026-06-26",
    "parentSetCode": null
  },
  {
    "code": "mul",
    "name": "Multiverse Legends",
    "setType": "masterpiece",
    "releasedAt": "2023-04-21",
    "parentSetCode": "mom"
  },
  {
    "code": "ncc",
    "name": "New Capenna Commander",
    "setType": "commander",
    "releasedAt": "2022-04-29",
    "parentSetCode": "snc"
  },
  {
    "code": "nec",
    "name": "Neon Dynasty Commander",
    "setType": "commander",
    "releasedAt": "2022-02-18",
    "parentSetCode": "neo"
  },
  {
    "code": "nem",
    "name": "Nemesis",
    "setType": "expansion",
    "releasedAt": "2000-02-14",
    "parentSetCode": null
  },
  {
    "code": "neo",
    "name": "Kamigawa: Neon Dynasty",
    "setType": "expansion",
    "releasedAt": "2022-02-18",
    "parentSetCode": null
  },
  {
    "code": "nph",
    "name": "New Phyrexia",
    "setType": "expansion",
    "releasedAt": "2011-05-13",
    "parentSetCode": null
  },
  {
    "code": "oarc",
    "name": "Archenemy Schemes",
    "setType": "archenemy",
    "releasedAt": "2010-06-18",
    "parentSetCode": "arc"
  },
  {
    "code": "ody",
    "name": "Odyssey",
    "setType": "expansion",
    "releasedAt": "2001-10-01",
    "parentSetCode": null
  },
  {
    "code": "oe01",
    "name": "Archenemy: Nicol Bolas Schemes",
    "setType": "archenemy",
    "releasedAt": "2017-06-16",
    "parentSetCode": "e01"
  },
  {
    "code": "ogw",
    "name": "Oath of the Gatewatch",
    "setType": "expansion",
    "releasedAt": "2016-01-22",
    "parentSetCode": null
  },
  {
    "code": "ohop",
    "name": "Planechase Planes",
    "setType": "planechase",
    "releasedAt": "2009-09-04",
    "parentSetCode": "hop"
  },
  {
    "code": "onc",
    "name": "Phyrexia: All Will Be One Commander",
    "setType": "commander",
    "releasedAt": "2023-02-10",
    "parentSetCode": "one"
  },
  {
    "code": "one",
    "name": "Phyrexia: All Will Be One",
    "setType": "expansion",
    "releasedAt": "2023-02-10",
    "parentSetCode": null
  },
  {
    "code": "ons",
    "name": "Onslaught",
    "setType": "expansion",
    "releasedAt": "2002-10-07",
    "parentSetCode": null
  },
  {
    "code": "opc2",
    "name": "Planechase 2012 Planes",
    "setType": "planechase",
    "releasedAt": "2012-06-01",
    "parentSetCode": "pc2"
  },
  {
    "code": "opca",
    "name": "Planechase Anthology Planes",
    "setType": "planechase",
    "releasedAt": "2016-11-25",
    "parentSetCode": "pca"
  },
  {
    "code": "ori",
    "name": "Magic Origins",
    "setType": "core",
    "releasedAt": "2015-07-17",
    "parentSetCode": null
  },
  {
    "code": "otc",
    "name": "Outlaws of Thunder Junction Commander",
    "setType": "commander",
    "releasedAt": "2024-04-19",
    "parentSetCode": "otj"
  },
  {
    "code": "otj",
    "name": "Outlaws of Thunder Junction",
    "setType": "expansion",
    "releasedAt": "2024-04-19",
    "parentSetCode": null
  },
  {
    "code": "otp",
    "name": "Breaking News",
    "setType": "masterpiece",
    "releasedAt": "2024-04-19",
    "parentSetCode": "otj"
  },
  {
    "code": "p02",
    "name": "Portal Second Age",
    "setType": "starter",
    "releasedAt": "1998-06-24",
    "parentSetCode": null
  },
  {
    "code": "p03",
    "name": "Magic Player Rewards 2003",
    "setType": "promo",
    "releasedAt": "2003-01-01",
    "parentSetCode": null
  },
  {
    "code": "p04",
    "name": "Magic Player Rewards 2004",
    "setType": "promo",
    "releasedAt": "2004-01-01",
    "parentSetCode": null
  },
  {
    "code": "p05",
    "name": "Magic Player Rewards 2005",
    "setType": "promo",
    "releasedAt": "2005-01-01",
    "parentSetCode": null
  },
  {
    "code": "p06",
    "name": "Magic Player Rewards 2006",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "p07",
    "name": "Magic Player Rewards 2007",
    "setType": "promo",
    "releasedAt": "2007-01-01",
    "parentSetCode": null
  },
  {
    "code": "p08",
    "name": "Magic Player Rewards 2008",
    "setType": "promo",
    "releasedAt": "2008-01-01",
    "parentSetCode": null
  },
  {
    "code": "p09",
    "name": "Magic Player Rewards 2009",
    "setType": "promo",
    "releasedAt": "2009-01-01",
    "parentSetCode": null
  },
  {
    "code": "p10",
    "name": "Magic Player Rewards 2010",
    "setType": "promo",
    "releasedAt": "2010-01-01",
    "parentSetCode": null
  },
  {
    "code": "p10e",
    "name": "Tenth Edition Promos",
    "setType": "promo",
    "releasedAt": "2007-07-13",
    "parentSetCode": "10e"
  },
  {
    "code": "p11",
    "name": "Magic Player Rewards 2011",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "p15a",
    "name": "15th Anniversary Cards",
    "setType": "promo",
    "releasedAt": "2008-04-01",
    "parentSetCode": null
  },
  {
    "code": "p22",
    "name": "Judge Gift Cards 2022",
    "setType": "promo",
    "releasedAt": "2022-01-01",
    "parentSetCode": null
  },
  {
    "code": "p23",
    "name": "Judge Gift Cards 2023",
    "setType": "promo",
    "releasedAt": "2023-01-01",
    "parentSetCode": null
  },
  {
    "code": "p2hg",
    "name": "Two-Headed Giant Tournament",
    "setType": "promo",
    "releasedAt": "2005-12-09",
    "parentSetCode": null
  },
  {
    "code": "p30a",
    "name": "30th Anniversary Play Promos",
    "setType": "promo",
    "releasedAt": "2022-09-02",
    "parentSetCode": "30a"
  },
  {
    "code": "p30h",
    "name": "30th Anniversary History Promos",
    "setType": "promo",
    "releasedAt": "2022-09-09",
    "parentSetCode": "30a"
  },
  {
    "code": "p30m",
    "name": "30th Anniversary Misc Promos",
    "setType": "promo",
    "releasedAt": "2022-09-02",
    "parentSetCode": "30a"
  },
  {
    "code": "p30t",
    "name": "30th Anniversary Celebration Tokyo",
    "setType": "promo",
    "releasedAt": "2023-09-01",
    "parentSetCode": "30a"
  },
  {
    "code": "p5dn",
    "name": "Fifth Dawn Promos",
    "setType": "promo",
    "releasedAt": "2004-06-04",
    "parentSetCode": "5dn"
  },
  {
    "code": "p8ed",
    "name": "Eighth Edition Promos",
    "setType": "promo",
    "releasedAt": "2003-07-28",
    "parentSetCode": "8ed"
  },
  {
    "code": "p9ed",
    "name": "Ninth Edition Promos",
    "setType": "promo",
    "releasedAt": "2005-07-29",
    "parentSetCode": "9ed"
  },
  {
    "code": "paer",
    "name": "Aether Revolt Promos",
    "setType": "promo",
    "releasedAt": "2017-01-20",
    "parentSetCode": "aer"
  },
  {
    "code": "pafr",
    "name": "Adventures in the Forgotten Realms Promos",
    "setType": "promo",
    "releasedAt": "2021-07-23",
    "parentSetCode": "afr"
  },
  {
    "code": "pakh",
    "name": "Amonkhet Promos",
    "setType": "promo",
    "releasedAt": "2017-04-28",
    "parentSetCode": "akh"
  },
  {
    "code": "pal00",
    "name": "Arena League 2000",
    "setType": "promo",
    "releasedAt": "2000-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal01",
    "name": "Arena League 2001",
    "setType": "promo",
    "releasedAt": "2001-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal02",
    "name": "Arena League 2002",
    "setType": "promo",
    "releasedAt": "2002-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal03",
    "name": "Arena League 2003",
    "setType": "promo",
    "releasedAt": "2003-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal04",
    "name": "Arena League 2004",
    "setType": "promo",
    "releasedAt": "2004-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal05",
    "name": "Arena League 2005",
    "setType": "promo",
    "releasedAt": "2005-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal06",
    "name": "Arena League 2006",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "pal99",
    "name": "Arena League 1999",
    "setType": "promo",
    "releasedAt": "1999-01-01",
    "parentSetCode": null
  },
  {
    "code": "pala",
    "name": "Shards of Alara Promos",
    "setType": "promo",
    "releasedAt": "2008-10-03",
    "parentSetCode": "ala"
  },
  {
    "code": "palp",
    "name": "Asia Pacific Land Program",
    "setType": "promo",
    "releasedAt": "1998-09-01",
    "parentSetCode": null
  },
  {
    "code": "papc",
    "name": "Apocalypse Promos",
    "setType": "promo",
    "releasedAt": "2001-06-04",
    "parentSetCode": "apc"
  },
  {
    "code": "parb",
    "name": "Alara Reborn Promos",
    "setType": "promo",
    "releasedAt": "2009-04-30",
    "parentSetCode": "arb"
  },
  {
    "code": "parl",
    "name": "Arena League 1996",
    "setType": "promo",
    "releasedAt": "1996-08-02",
    "parentSetCode": null
  },
  {
    "code": "pavr",
    "name": "Avacyn Restored Promos",
    "setType": "promo",
    "releasedAt": "2012-04-28",
    "parentSetCode": "avr"
  },
  {
    "code": "pbbd",
    "name": "Battlebond Promos",
    "setType": "promo",
    "releasedAt": "2018-06-08",
    "parentSetCode": "bbd"
  },
  {
    "code": "pbfz",
    "name": "Battle for Zendikar Promos",
    "setType": "promo",
    "releasedAt": "2015-10-02",
    "parentSetCode": "bfz"
  },
  {
    "code": "pbig",
    "name": "The Big Score Promos",
    "setType": "promo",
    "releasedAt": "2025-08-01",
    "parentSetCode": "big"
  },
  {
    "code": "pblb",
    "name": "Bloomburrow Promos",
    "setType": "promo",
    "releasedAt": "2024-08-02",
    "parentSetCode": "blb"
  },
  {
    "code": "pbng",
    "name": "Born of the Gods Promos",
    "setType": "promo",
    "releasedAt": "2014-02-01",
    "parentSetCode": "bng"
  },
  {
    "code": "pbok",
    "name": "Betrayers of Kamigawa Promos",
    "setType": "promo",
    "releasedAt": "2005-02-04",
    "parentSetCode": "bok"
  },
  {
    "code": "pbro",
    "name": "The Brothers' War Promos",
    "setType": "promo",
    "releasedAt": "2022-11-18",
    "parentSetCode": "bro"
  },
  {
    "code": "pc2",
    "name": "Planechase 2012",
    "setType": "planechase",
    "releasedAt": "2012-06-01",
    "parentSetCode": null
  },
  {
    "code": "pca",
    "name": "Planechase Anthology",
    "setType": "planechase",
    "releasedAt": "2016-11-25",
    "parentSetCode": null
  },
  {
    "code": "pcbb",
    "name": "Cowboy Bebop",
    "setType": "promo",
    "releasedAt": "2024-08-02",
    "parentSetCode": null
  },
  {
    "code": "pchk",
    "name": "Champions of Kamigawa Promos",
    "setType": "promo",
    "releasedAt": "2004-10-01",
    "parentSetCode": "chk"
  },
  {
    "code": "pclb",
    "name": "Battle for Baldur's Gate Promos",
    "setType": "promo",
    "releasedAt": "2022-06-10",
    "parentSetCode": "clb"
  },
  {
    "code": "pcmp",
    "name": "Champs and States",
    "setType": "promo",
    "releasedAt": "2006-03-18",
    "parentSetCode": null
  },
  {
    "code": "pcmr",
    "name": "Commander Legends Promos",
    "setType": "promo",
    "releasedAt": "2020-11-20",
    "parentSetCode": "cmr"
  },
  {
    "code": "pcns",
    "name": "Conspiracy Promos",
    "setType": "promo",
    "releasedAt": "2014-06-06",
    "parentSetCode": "cns"
  },
  {
    "code": "pcon",
    "name": "Conflux Promos",
    "setType": "promo",
    "releasedAt": "2009-02-06",
    "parentSetCode": "con"
  },
  {
    "code": "pcsp",
    "name": "Coldsnap Promos",
    "setType": "promo",
    "releasedAt": "2006-07-21",
    "parentSetCode": "csp"
  },
  {
    "code": "pcy",
    "name": "Prophecy",
    "setType": "expansion",
    "releasedAt": "2000-06-05",
    "parentSetCode": null
  },
  {
    "code": "pd2",
    "name": "Premium Deck Series: Fire and Lightning",
    "setType": "premium_deck",
    "releasedAt": "2010-11-19",
    "parentSetCode": null
  },
  {
    "code": "pd3",
    "name": "Premium Deck Series: Graveborn",
    "setType": "premium_deck",
    "releasedAt": "2011-11-18",
    "parentSetCode": null
  },
  {
    "code": "pdft",
    "name": "Aetherdrift Promos",
    "setType": "promo",
    "releasedAt": "2025-02-14",
    "parentSetCode": "dft"
  },
  {
    "code": "pdgm",
    "name": "Dragon's Maze Promos",
    "setType": "promo",
    "releasedAt": "2013-04-27",
    "parentSetCode": "dgm"
  },
  {
    "code": "pdis",
    "name": "Dissension Promos",
    "setType": "promo",
    "releasedAt": "2006-05-05",
    "parentSetCode": "dis"
  },
  {
    "code": "pdka",
    "name": "Dark Ascension Promos",
    "setType": "promo",
    "releasedAt": "2012-01-28",
    "parentSetCode": "dka"
  },
  {
    "code": "pdmu",
    "name": "Dominaria United Promos",
    "setType": "promo",
    "releasedAt": "2022-09-09",
    "parentSetCode": "dmu"
  },
  {
    "code": "pdom",
    "name": "Dominaria Promos",
    "setType": "promo",
    "releasedAt": "2018-04-27",
    "parentSetCode": "dom"
  },
  {
    "code": "pdp10",
    "name": "Duels of the Planeswalkers 2010 Promos",
    "setType": "promo",
    "releasedAt": "2010-01-01",
    "parentSetCode": null
  },
  {
    "code": "pdp12",
    "name": "Duels of the Planeswalkers 2012 Promos",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "pdp13",
    "name": "Duels of the Planeswalkers 2013 Promos",
    "setType": "promo",
    "releasedAt": "2012-01-01",
    "parentSetCode": null
  },
  {
    "code": "pdp14",
    "name": "Duels of the Planeswalkers 2014 Promos",
    "setType": "promo",
    "releasedAt": "2013-01-01",
    "parentSetCode": null
  },
  {
    "code": "pdp15",
    "name": "Duels of the Planeswalkers 2015 Promos",
    "setType": "promo",
    "releasedAt": "2014-07-09",
    "parentSetCode": null
  },
  {
    "code": "pdrc",
    "name": "Dragon Con",
    "setType": "promo",
    "releasedAt": "1994-07-15",
    "parentSetCode": null
  },
  {
    "code": "pdsk",
    "name": "Duskmourn: House of Horror Promos",
    "setType": "promo",
    "releasedAt": "2024-09-27",
    "parentSetCode": "dsk"
  },
  {
    "code": "pdst",
    "name": "Darksteel Promos",
    "setType": "promo",
    "releasedAt": "2004-02-06",
    "parentSetCode": "dst"
  },
  {
    "code": "pdtk",
    "name": "Dragons of Tarkir Promos",
    "setType": "promo",
    "releasedAt": "2015-03-27",
    "parentSetCode": "dtk"
  },
  {
    "code": "pdtp",
    "name": "Duels of the Planeswalkers 2009 Promos",
    "setType": "promo",
    "releasedAt": "2009-01-01",
    "parentSetCode": null
  },
  {
    "code": "pecl",
    "name": "Lorwyn Eclipsed Promos",
    "setType": "promo",
    "releasedAt": "2026-01-23",
    "parentSetCode": "ecl"
  },
  {
    "code": "peld",
    "name": "Throne of Eldraine Promos",
    "setType": "promo",
    "releasedAt": "2019-10-04",
    "parentSetCode": "eld"
  },
  {
    "code": "pelp",
    "name": "European Land Program",
    "setType": "promo",
    "releasedAt": "2000-02-05",
    "parentSetCode": null
  },
  {
    "code": "pemn",
    "name": "Eldritch Moon Promos",
    "setType": "promo",
    "releasedAt": "2016-07-22",
    "parentSetCode": "emn"
  },
  {
    "code": "peoe",
    "name": "Edge of Eternities Promos",
    "setType": "promo",
    "releasedAt": "2025-08-01",
    "parentSetCode": "eoe"
  },
  {
    "code": "peve",
    "name": "Eventide Promos",
    "setType": "promo",
    "releasedAt": "2008-07-25",
    "parentSetCode": "eve"
  },
  {
    "code": "pewk",
    "name": "Eternal Weekend",
    "setType": "promo",
    "releasedAt": "2022-11-26",
    "parentSetCode": null
  },
  {
    "code": "pexo",
    "name": "Exodus Promos",
    "setType": "promo",
    "releasedAt": "1998-06-15",
    "parentSetCode": "exo"
  },
  {
    "code": "pf19",
    "name": "MagicFest 2019",
    "setType": "promo",
    "releasedAt": "2019-01-01",
    "parentSetCode": null
  },
  {
    "code": "pf20",
    "name": "MagicFest 2020",
    "setType": "promo",
    "releasedAt": "2020-01-01",
    "parentSetCode": null
  },
  {
    "code": "pf23",
    "name": "MagicFest 2023",
    "setType": "promo",
    "releasedAt": "2023-07-01",
    "parentSetCode": null
  },
  {
    "code": "pf24",
    "name": "MagicFest 2024",
    "setType": "promo",
    "releasedAt": "2024-01-01",
    "parentSetCode": null
  },
  {
    "code": "pf25",
    "name": "MagicFest 2025",
    "setType": "promo",
    "releasedAt": "2025-01-01",
    "parentSetCode": null
  },
  {
    "code": "pf26",
    "name": "MagicFest 2026",
    "setType": "promo",
    "releasedAt": "2026-01-01",
    "parentSetCode": null
  },
  {
    "code": "pfdn",
    "name": "Foundations Promos",
    "setType": "promo",
    "releasedAt": "2024-11-15",
    "parentSetCode": "fdn"
  },
  {
    "code": "pfin",
    "name": "Final Fantasy Promos",
    "setType": "promo",
    "releasedAt": "2025-06-13",
    "parentSetCode": "fin"
  },
  {
    "code": "pfrf",
    "name": "Fate Reforged Promos",
    "setType": "promo",
    "releasedAt": "2015-01-23",
    "parentSetCode": "frf"
  },
  {
    "code": "pfut",
    "name": "Future Sight Promos",
    "setType": "promo",
    "releasedAt": "2007-05-04",
    "parentSetCode": "fut"
  },
  {
    "code": "pgpt",
    "name": "Guildpact Promos",
    "setType": "promo",
    "releasedAt": "2006-02-03",
    "parentSetCode": "gpt"
  },
  {
    "code": "pgpx",
    "name": "Grand Prix Promos",
    "setType": "promo",
    "releasedAt": "2007-02-24",
    "parentSetCode": null
  },
  {
    "code": "pgrn",
    "name": "Guilds of Ravnica Promos",
    "setType": "promo",
    "releasedAt": "2018-10-05",
    "parentSetCode": "grn"
  },
  {
    "code": "pgru",
    "name": "Guru",
    "setType": "promo",
    "releasedAt": "1999-07-12",
    "parentSetCode": null
  },
  {
    "code": "pgtc",
    "name": "Gatecrash Promos",
    "setType": "promo",
    "releasedAt": "2013-01-26",
    "parentSetCode": "gtc"
  },
  {
    "code": "ph17",
    "name": "2017 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2018-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph18",
    "name": "2018 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2019-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph19",
    "name": "2019 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2020-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph20",
    "name": "2020 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2021-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph21",
    "name": "2021 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2022-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph22",
    "name": "2022 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2023-08-01",
    "parentSetCode": null
  },
  {
    "code": "ph23",
    "name": "2023 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2025-08-24",
    "parentSetCode": null
  },
  {
    "code": "phop",
    "name": "Planechase Promos",
    "setType": "promo",
    "releasedAt": "2009-09-04",
    "parentSetCode": "hop"
  },
  {
    "code": "phou",
    "name": "Hour of Devastation Promos",
    "setType": "promo",
    "releasedAt": "2017-07-14",
    "parentSetCode": "hou"
  },
  {
    "code": "phpr",
    "name": "HarperPrism Book Promos",
    "setType": "promo",
    "releasedAt": "1994-09-01",
    "parentSetCode": null
  },
  {
    "code": "phtr",
    "name": "2016 Heroes of the Realm",
    "setType": "funny",
    "releasedAt": "2017-09-20",
    "parentSetCode": null
  },
  {
    "code": "phuk",
    "name": "Hachette UK",
    "setType": "box",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "pidw",
    "name": "IDW Comics Inserts",
    "setType": "promo",
    "releasedAt": "2012-01-01",
    "parentSetCode": null
  },
  {
    "code": "piko",
    "name": "Ikoria: Lair of Behemoths Promos",
    "setType": "promo",
    "releasedAt": "2020-04-24",
    "parentSetCode": "iko"
  },
  {
    "code": "pinv",
    "name": "Invasion Promos",
    "setType": "promo",
    "releasedAt": "2000-10-02",
    "parentSetCode": "inv"
  },
  {
    "code": "pip",
    "name": "Fallout",
    "setType": "commander",
    "releasedAt": "2024-03-08",
    "parentSetCode": null
  },
  {
    "code": "pisd",
    "name": "Innistrad Promos",
    "setType": "promo",
    "releasedAt": "2011-09-24",
    "parentSetCode": "isd"
  },
  {
    "code": "pj21",
    "name": "Judge Gift Cards 2021",
    "setType": "promo",
    "releasedAt": "2021-01-01",
    "parentSetCode": null
  },
  {
    "code": "pjas",
    "name": "Junior APAC Series",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "pjjt",
    "name": "Japan Junior Tournament",
    "setType": "promo",
    "releasedAt": "2003-01-01",
    "parentSetCode": null
  },
  {
    "code": "pjou",
    "name": "Journey into Nyx Promos",
    "setType": "promo",
    "releasedAt": "2014-04-26",
    "parentSetCode": "jou"
  },
  {
    "code": "pjsc",
    "name": "Japan Standard Cup",
    "setType": "promo",
    "releasedAt": "2025-02-09",
    "parentSetCode": null
  },
  {
    "code": "pjse",
    "name": "Junior Series Europe",
    "setType": "promo",
    "releasedAt": "2005-01-01",
    "parentSetCode": null
  },
  {
    "code": "pjud",
    "name": "Judgment Promos",
    "setType": "promo",
    "releasedAt": "2002-05-27",
    "parentSetCode": "jud"
  },
  {
    "code": "pkhm",
    "name": "Kaldheim Promos",
    "setType": "promo",
    "releasedAt": "2021-02-05",
    "parentSetCode": "khm"
  },
  {
    "code": "pkld",
    "name": "Kaladesh Promos",
    "setType": "promo",
    "releasedAt": "2016-09-30",
    "parentSetCode": "kld"
  },
  {
    "code": "pktk",
    "name": "Khans of Tarkir Promos",
    "setType": "promo",
    "releasedAt": "2014-09-26",
    "parentSetCode": "ktk"
  },
  {
    "code": "pl21",
    "name": "Year of the Ox 2021",
    "setType": "promo",
    "releasedAt": "2021-01-25",
    "parentSetCode": null
  },
  {
    "code": "pl22",
    "name": "Year of the Tiger 2022",
    "setType": "promo",
    "releasedAt": "2022-02-25",
    "parentSetCode": null
  },
  {
    "code": "pl23",
    "name": "Year of the Rabbit 2023",
    "setType": "promo",
    "releasedAt": "2023-02-10",
    "parentSetCode": null
  },
  {
    "code": "pl24",
    "name": "Year of the Dragon 2024",
    "setType": "promo",
    "releasedAt": "2024-02-08",
    "parentSetCode": null
  },
  {
    "code": "pl25",
    "name": "Year of the Snake 2025",
    "setType": "promo",
    "releasedAt": "2025-02-14",
    "parentSetCode": null
  },
  {
    "code": "pl26",
    "name": "Year of the Horse 2026",
    "setType": "promo",
    "releasedAt": "2026-02-17",
    "parentSetCode": null
  },
  {
    "code": "plc",
    "name": "Planar Chaos",
    "setType": "expansion",
    "releasedAt": "2007-02-02",
    "parentSetCode": null
  },
  {
    "code": "plci",
    "name": "The Lost Caverns of Ixalan Promos",
    "setType": "promo",
    "releasedAt": "2023-11-17",
    "parentSetCode": "lci"
  },
  {
    "code": "plg20",
    "name": "Love Your LGS 2020",
    "setType": "promo",
    "releasedAt": "2020-05-18",
    "parentSetCode": null
  },
  {
    "code": "plg21",
    "name": "Love Your LGS 2021",
    "setType": "promo",
    "releasedAt": "2021-06-22",
    "parentSetCode": null
  },
  {
    "code": "plg22",
    "name": "Love Your LGS 2022",
    "setType": "promo",
    "releasedAt": "2022-07-01",
    "parentSetCode": null
  },
  {
    "code": "plg24",
    "name": "Love Your LGS 2024",
    "setType": "promo",
    "releasedAt": "2024-08-06",
    "parentSetCode": null
  },
  {
    "code": "plg25",
    "name": "Love Your LGS 2025",
    "setType": "promo",
    "releasedAt": "2025-03-26",
    "parentSetCode": null
  },
  {
    "code": "plgm",
    "name": "DCI Legend Membership",
    "setType": "promo",
    "releasedAt": "1996-07-01",
    "parentSetCode": null
  },
  {
    "code": "plgn",
    "name": "Legions Promos",
    "setType": "promo",
    "releasedAt": "2003-02-03",
    "parentSetCode": "lgn"
  },
  {
    "code": "plny",
    "name": "Lunar New Year 2018",
    "setType": "promo",
    "releasedAt": "2018-02-16",
    "parentSetCode": null
  },
  {
    "code": "plrw",
    "name": "Lorwyn Promos",
    "setType": "promo",
    "releasedAt": "2007-10-12",
    "parentSetCode": "lrw"
  },
  {
    "code": "pls",
    "name": "Planeshift",
    "setType": "expansion",
    "releasedAt": "2001-02-05",
    "parentSetCode": null
  },
  {
    "code": "plst",
    "name": "The List",
    "setType": "masters",
    "releasedAt": "2020-09-26",
    "parentSetCode": null
  },
  {
    "code": "pltc",
    "name": "Tales of Middle-earth Deluxe Commander Kit",
    "setType": "promo",
    "releasedAt": "2024-10-16",
    "parentSetCode": "ltr"
  },
  {
    "code": "pltr",
    "name": "Tales of Middle-earth Promos",
    "setType": "promo",
    "releasedAt": "2023-06-23",
    "parentSetCode": "ltr"
  },
  {
    "code": "pm10",
    "name": "Magic 2010 Promos",
    "setType": "promo",
    "releasedAt": "2009-07-16",
    "parentSetCode": "m10"
  },
  {
    "code": "pm11",
    "name": "Magic 2011 Promos",
    "setType": "promo",
    "releasedAt": "2010-07-15",
    "parentSetCode": "m11"
  },
  {
    "code": "pm12",
    "name": "Magic 2012 Promos",
    "setType": "promo",
    "releasedAt": "2011-07-14",
    "parentSetCode": "m12"
  },
  {
    "code": "pm13",
    "name": "Magic 2013 Promos",
    "setType": "promo",
    "releasedAt": "2012-07-12",
    "parentSetCode": "m13"
  },
  {
    "code": "pm14",
    "name": "Magic 2014 Promos",
    "setType": "promo",
    "releasedAt": "2013-07-18",
    "parentSetCode": "m14"
  },
  {
    "code": "pm15",
    "name": "Magic 2015 Promos",
    "setType": "promo",
    "releasedAt": "2014-07-17",
    "parentSetCode": "m15"
  },
  {
    "code": "pm19",
    "name": "Core Set 2019 Promos",
    "setType": "promo",
    "releasedAt": "2018-07-13",
    "parentSetCode": "m19"
  },
  {
    "code": "pm20",
    "name": "Core Set 2020 Promos",
    "setType": "promo",
    "releasedAt": "2019-07-12",
    "parentSetCode": "m20"
  },
  {
    "code": "pm21",
    "name": "Core Set 2021 Promos",
    "setType": "promo",
    "releasedAt": "2020-07-03",
    "parentSetCode": "m21"
  },
  {
    "code": "pmat",
    "name": "March of the Machine: The Aftermath Promos",
    "setType": "promo",
    "releasedAt": "2023-11-17",
    "parentSetCode": "mat"
  },
  {
    "code": "pmbs",
    "name": "Mirrodin Besieged Promos",
    "setType": "promo",
    "releasedAt": "2011-02-03",
    "parentSetCode": "mbs"
  },
  {
    "code": "pmda",
    "name": "Magic × Duel Masters Promos",
    "setType": "promo",
    "releasedAt": "2023-09-08",
    "parentSetCode": null
  },
  {
    "code": "pmei",
    "name": "Media and Collaboration Promos",
    "setType": "promo",
    "releasedAt": "1995-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmh1",
    "name": "Modern Horizons Promos",
    "setType": "promo",
    "releasedAt": "2019-06-14",
    "parentSetCode": "mh1"
  },
  {
    "code": "pmh2",
    "name": "Modern Horizons 2 Promos",
    "setType": "promo",
    "releasedAt": "2021-06-18",
    "parentSetCode": "mh2"
  },
  {
    "code": "pmh3",
    "name": "Modern Horizons 3 Promos",
    "setType": "promo",
    "releasedAt": "2024-06-14",
    "parentSetCode": "mh3"
  },
  {
    "code": "pmid",
    "name": "Innistrad: Midnight Hunt Promos",
    "setType": "promo",
    "releasedAt": "2021-09-24",
    "parentSetCode": "mid"
  },
  {
    "code": "pmkm",
    "name": "Murders at Karlov Manor Promos",
    "setType": "promo",
    "releasedAt": "2024-02-09",
    "parentSetCode": "mkm"
  },
  {
    "code": "pmmq",
    "name": "Mercadian Masques Promos",
    "setType": "promo",
    "releasedAt": "1999-10-04",
    "parentSetCode": "mmq"
  },
  {
    "code": "pmom",
    "name": "March of the Machine Promos",
    "setType": "promo",
    "releasedAt": "2023-04-21",
    "parentSetCode": "mom"
  },
  {
    "code": "pmor",
    "name": "Morningtide Promos",
    "setType": "promo",
    "releasedAt": "2008-02-01",
    "parentSetCode": "mor"
  },
  {
    "code": "pmps",
    "name": "Magic Premiere Shop 2005",
    "setType": "promo",
    "releasedAt": "2005-10-07",
    "parentSetCode": null
  },
  {
    "code": "pmps06",
    "name": "Magic Premiere Shop 2006",
    "setType": "promo",
    "releasedAt": "2006-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmps07",
    "name": "Magic Premiere Shop 2007",
    "setType": "promo",
    "releasedAt": "2007-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmps08",
    "name": "Magic Premiere Shop 2008",
    "setType": "promo",
    "releasedAt": "2008-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmps09",
    "name": "Magic Premiere Shop 2009",
    "setType": "promo",
    "releasedAt": "2009-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmps10",
    "name": "Magic Premiere Shop 2010",
    "setType": "promo",
    "releasedAt": "2010-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmps11",
    "name": "Magic Premiere Shop 2011",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "pmrd",
    "name": "Mirrodin Promos",
    "setType": "promo",
    "releasedAt": "2004-06-04",
    "parentSetCode": "mrd"
  },
  {
    "code": "pnat",
    "name": "Nationals Promos",
    "setType": "promo",
    "releasedAt": "2018-01-25",
    "parentSetCode": null
  },
  {
    "code": "pncc",
    "name": "New Capenna Commander Promos",
    "setType": "promo",
    "releasedAt": "2022-04-29",
    "parentSetCode": "ncc"
  },
  {
    "code": "pnem",
    "name": "Nemesis Promos",
    "setType": "promo",
    "releasedAt": "2000-02-14",
    "parentSetCode": "nem"
  },
  {
    "code": "pneo",
    "name": "Kamigawa: Neon Dynasty Promos",
    "setType": "promo",
    "releasedAt": "2022-02-18",
    "parentSetCode": "neo"
  },
  {
    "code": "pnph",
    "name": "New Phyrexia Promos",
    "setType": "promo",
    "releasedAt": "2011-05-12",
    "parentSetCode": "nph"
  },
  {
    "code": "pody",
    "name": "Odyssey Promos",
    "setType": "promo",
    "releasedAt": "2001-10-01",
    "parentSetCode": "ody"
  },
  {
    "code": "pogw",
    "name": "Oath of the Gatewatch Promos",
    "setType": "promo",
    "releasedAt": "2016-01-22",
    "parentSetCode": "ogw"
  },
  {
    "code": "pone",
    "name": "Phyrexia: All Will Be One Promos",
    "setType": "promo",
    "releasedAt": "2023-02-10",
    "parentSetCode": "one"
  },
  {
    "code": "pons",
    "name": "Onslaught Promos",
    "setType": "promo",
    "releasedAt": "2002-09-28",
    "parentSetCode": "ons"
  },
  {
    "code": "por",
    "name": "Portal",
    "setType": "starter",
    "releasedAt": "1997-05-01",
    "parentSetCode": null
  },
  {
    "code": "pori",
    "name": "Magic Origins Promos",
    "setType": "promo",
    "releasedAt": "2015-07-17",
    "parentSetCode": "ori"
  },
  {
    "code": "potj",
    "name": "Outlaws of Thunder Junction Promos",
    "setType": "promo",
    "releasedAt": "2024-04-19",
    "parentSetCode": "otj"
  },
  {
    "code": "ppcy",
    "name": "Prophecy Promos",
    "setType": "promo",
    "releasedAt": "2000-06-05",
    "parentSetCode": "pcy"
  },
  {
    "code": "pplc",
    "name": "Planar Chaos Promos",
    "setType": "promo",
    "releasedAt": "2007-02-02",
    "parentSetCode": "plc"
  },
  {
    "code": "ppls",
    "name": "Planeshift Promos",
    "setType": "promo",
    "releasedAt": "2001-02-05",
    "parentSetCode": "pls"
  },
  {
    "code": "ppp1",
    "name": "M20 Promo Packs",
    "setType": "promo",
    "releasedAt": "2019-07-12",
    "parentSetCode": "m20"
  },
  {
    "code": "ppro",
    "name": "Pro Tour Promos",
    "setType": "promo",
    "releasedAt": "2007-02-09",
    "parentSetCode": null
  },
  {
    "code": "pptk",
    "name": "Portal Three Kingdoms Promos",
    "setType": "promo",
    "releasedAt": "1999-05-01",
    "parentSetCode": "ptk"
  },
  {
    "code": "pr2",
    "name": "Magic Player Rewards 2002",
    "setType": "promo",
    "releasedAt": "2002-01-01",
    "parentSetCode": null
  },
  {
    "code": "pr23",
    "name": "Regional Championship Qualifiers 2023",
    "setType": "promo",
    "releasedAt": "2023-01-07",
    "parentSetCode": null
  },
  {
    "code": "prav",
    "name": "Ravnica: City of Guilds Promos",
    "setType": "promo",
    "releasedAt": "2005-10-07",
    "parentSetCode": "rav"
  },
  {
    "code": "prcq",
    "name": "Regional Championship Qualifiers 2022",
    "setType": "promo",
    "releasedAt": "2022-10-01",
    "parentSetCode": null
  },
  {
    "code": "pred",
    "name": "Redemption Program",
    "setType": "promo",
    "releasedAt": "1996-10-01",
    "parentSetCode": null
  },
  {
    "code": "prix",
    "name": "Rivals of Ixalan Promos",
    "setType": "promo",
    "releasedAt": "2018-01-19",
    "parentSetCode": "rix"
  },
  {
    "code": "prna",
    "name": "Ravnica Allegiance Promos",
    "setType": "promo",
    "releasedAt": "2019-01-25",
    "parentSetCode": "rna"
  },
  {
    "code": "proe",
    "name": "Rise of the Eldrazi Promos",
    "setType": "promo",
    "releasedAt": "2010-04-23",
    "parentSetCode": "roe"
  },
  {
    "code": "prtr",
    "name": "Return to Ravnica Promos",
    "setType": "promo",
    "releasedAt": "2012-10-05",
    "parentSetCode": "rtr"
  },
  {
    "code": "prw2",
    "name": "RNA Ravnica Weekend",
    "setType": "promo",
    "releasedAt": "2019-02-16",
    "parentSetCode": "rna"
  },
  {
    "code": "prwk",
    "name": "GRN Ravnica Weekend",
    "setType": "promo",
    "releasedAt": "2018-11-09",
    "parentSetCode": "grn"
  },
  {
    "code": "ps11",
    "name": "Salvat 2011",
    "setType": "box",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "ps14",
    "name": "San Diego Comic-Con 2014",
    "setType": "promo",
    "releasedAt": "2014-07-08",
    "parentSetCode": null
  },
  {
    "code": "ps15",
    "name": "San Diego Comic-Con 2015",
    "setType": "promo",
    "releasedAt": "2015-07-09",
    "parentSetCode": null
  },
  {
    "code": "ps16",
    "name": "San Diego Comic-Con 2016",
    "setType": "promo",
    "releasedAt": "2016-10-01",
    "parentSetCode": null
  },
  {
    "code": "ps17",
    "name": "San Diego Comic-Con 2017",
    "setType": "promo",
    "releasedAt": "2017-07-20",
    "parentSetCode": null
  },
  {
    "code": "ps18",
    "name": "San Diego Comic-Con 2018",
    "setType": "promo",
    "releasedAt": "2018-07-19",
    "parentSetCode": null
  },
  {
    "code": "ps19",
    "name": "San Diego Comic-Con 2019",
    "setType": "promo",
    "releasedAt": "2019-07-18",
    "parentSetCode": null
  },
  {
    "code": "psal",
    "name": "Salvat 2005",
    "setType": "box",
    "releasedAt": "2005-08-22",
    "parentSetCode": null
  },
  {
    "code": "pscg",
    "name": "Scourge Promos",
    "setType": "promo",
    "releasedAt": "2003-05-26",
    "parentSetCode": "scg"
  },
  {
    "code": "psdc",
    "name": "San Diego Comic-Con 2013",
    "setType": "promo",
    "releasedAt": "2013-07-18",
    "parentSetCode": null
  },
  {
    "code": "pshm",
    "name": "Shadowmoor Promos",
    "setType": "promo",
    "releasedAt": "2008-05-02",
    "parentSetCode": "shm"
  },
  {
    "code": "psnc",
    "name": "Streets of New Capenna Promos",
    "setType": "promo",
    "releasedAt": "2022-04-29",
    "parentSetCode": "snc"
  },
  {
    "code": "psoi",
    "name": "Shadows over Innistrad Promos",
    "setType": "promo",
    "releasedAt": "2016-04-08",
    "parentSetCode": "soi"
  },
  {
    "code": "psok",
    "name": "Saviors of Kamigawa Promos",
    "setType": "promo",
    "releasedAt": "2005-06-03",
    "parentSetCode": "sok"
  },
  {
    "code": "psom",
    "name": "Scars of Mirrodin Promos",
    "setType": "promo",
    "releasedAt": "2010-09-30",
    "parentSetCode": "som"
  },
  {
    "code": "psos",
    "name": "Secrets of Strixhaven Promos",
    "setType": "promo",
    "releasedAt": "2026-04-24",
    "parentSetCode": "sos"
  },
  {
    "code": "pspl",
    "name": "Spotlight Series",
    "setType": "promo",
    "releasedAt": "2025-01-03",
    "parentSetCode": null
  },
  {
    "code": "pspm",
    "name": "Marvel's Spider-Man Promos",
    "setType": "promo",
    "releasedAt": "2025-09-26",
    "parentSetCode": "spm"
  },
  {
    "code": "pss1",
    "name": "BFZ Standard Series",
    "setType": "promo",
    "releasedAt": "2015-10-02",
    "parentSetCode": "bfz"
  },
  {
    "code": "pss2",
    "name": "XLN Standard Showdown",
    "setType": "promo",
    "releasedAt": "2017-09-29",
    "parentSetCode": "xln"
  },
  {
    "code": "pss3",
    "name": "M19 Standard Showdown",
    "setType": "promo",
    "releasedAt": "2018-07-13",
    "parentSetCode": "m19"
  },
  {
    "code": "pss4",
    "name": "MKM Standard Showdown",
    "setType": "promo",
    "releasedAt": "2024-02-10",
    "parentSetCode": "mkm"
  },
  {
    "code": "pss5",
    "name": "FIN Standard Showdown",
    "setType": "promo",
    "releasedAt": "2025-06-13",
    "parentSetCode": "fin"
  },
  {
    "code": "psth",
    "name": "Stronghold Promos",
    "setType": "promo",
    "releasedAt": "1998-03-02",
    "parentSetCode": "sth"
  },
  {
    "code": "pstx",
    "name": "Strixhaven: School of Mages Promos",
    "setType": "promo",
    "releasedAt": "2021-04-23",
    "parentSetCode": "stx"
  },
  {
    "code": "psus",
    "name": "Junior Super Series",
    "setType": "promo",
    "releasedAt": "1999-12-01",
    "parentSetCode": null
  },
  {
    "code": "psvc",
    "name": "Summer Vacation Promos 2022",
    "setType": "promo",
    "releasedAt": "2022-08-01",
    "parentSetCode": null
  },
  {
    "code": "ptdm",
    "name": "Tarkir: Dragonstorm Promos",
    "setType": "promo",
    "releasedAt": "2025-04-11",
    "parentSetCode": "tdm"
  },
  {
    "code": "ptg",
    "name": "Ponies: The Galloping",
    "setType": "funny",
    "releasedAt": "2019-10-22",
    "parentSetCode": null
  },
  {
    "code": "pthb",
    "name": "Theros Beyond Death Promos",
    "setType": "promo",
    "releasedAt": "2020-01-24",
    "parentSetCode": "thb"
  },
  {
    "code": "pths",
    "name": "Theros Promos",
    "setType": "promo",
    "releasedAt": "2013-09-21",
    "parentSetCode": "ths"
  },
  {
    "code": "ptk",
    "name": "Portal Three Kingdoms",
    "setType": "starter",
    "releasedAt": "1999-05-01",
    "parentSetCode": null
  },
  {
    "code": "ptkdf",
    "name": "Tarkir Dragonfury",
    "setType": "promo",
    "releasedAt": "2015-04-03",
    "parentSetCode": "dtk"
  },
  {
    "code": "ptla",
    "name": "Avatar: The Last Airbender Promos",
    "setType": "promo",
    "releasedAt": "2025-11-21",
    "parentSetCode": "tla"
  },
  {
    "code": "ptmp",
    "name": "Tempest Promos",
    "setType": "promo",
    "releasedAt": "1997-10-14",
    "parentSetCode": "tmp"
  },
  {
    "code": "ptor",
    "name": "Torment Promos",
    "setType": "promo",
    "releasedAt": "2002-02-04",
    "parentSetCode": "tor"
  },
  {
    "code": "ptsnc",
    "name": "Streets of New Capenna Southeast Asia Tokens",
    "setType": "promo",
    "releasedAt": "2022-04-30",
    "parentSetCode": "psnc"
  },
  {
    "code": "ptsp",
    "name": "Time Spiral Promos",
    "setType": "promo",
    "releasedAt": "2006-10-06",
    "parentSetCode": "tsp"
  },
  {
    "code": "ptsr",
    "name": "Time Spiral Remastered Promos",
    "setType": "promo",
    "releasedAt": "2023-09-08",
    "parentSetCode": "tsr"
  },
  {
    "code": "puds",
    "name": "Urza's Destiny Promos",
    "setType": "promo",
    "releasedAt": "1999-06-07",
    "parentSetCode": "uds"
  },
  {
    "code": "pulg",
    "name": "Urza's Legacy Promos",
    "setType": "promo",
    "releasedAt": "1999-02-15",
    "parentSetCode": "ulg"
  },
  {
    "code": "puma",
    "name": "Ultimate Box Topper",
    "setType": "masterpiece",
    "releasedAt": "2018-12-07",
    "parentSetCode": "uma"
  },
  {
    "code": "punh",
    "name": "Unhinged Promos",
    "setType": "promo",
    "releasedAt": "2004-11-19",
    "parentSetCode": "unh"
  },
  {
    "code": "punk",
    "name": "Black Lotus Unknown Planechase",
    "setType": "funny",
    "releasedAt": "2024-02-24",
    "parentSetCode": "unk"
  },
  {
    "code": "purl",
    "name": "URL/Convention Promos",
    "setType": "promo",
    "releasedAt": "2009-02-08",
    "parentSetCode": null
  },
  {
    "code": "pusg",
    "name": "Urza's Saga Promos",
    "setType": "promo",
    "releasedAt": "1998-10-12",
    "parentSetCode": "usg"
  },
  {
    "code": "pust",
    "name": "Unstable Promos",
    "setType": "promo",
    "releasedAt": "2017-12-08",
    "parentSetCode": "ust"
  },
  {
    "code": "pvow",
    "name": "Innistrad: Crimson Vow Promos",
    "setType": "promo",
    "releasedAt": "2021-11-19",
    "parentSetCode": "vow"
  },
  {
    "code": "pw11",
    "name": "Wizards Play Network 2011",
    "setType": "promo",
    "releasedAt": "2011-01-01",
    "parentSetCode": null
  },
  {
    "code": "pw12",
    "name": "Wizards Play Network 2012",
    "setType": "promo",
    "releasedAt": "2012-01-01",
    "parentSetCode": null
  },
  {
    "code": "pw21",
    "name": "Wizards Play Network 2021",
    "setType": "promo",
    "releasedAt": "2021-06-18",
    "parentSetCode": null
  },
  {
    "code": "pw22",
    "name": "Wizards Play Network 2022",
    "setType": "promo",
    "releasedAt": "2022-03-05",
    "parentSetCode": null
  },
  {
    "code": "pw23",
    "name": "Wizards Play Network 2023",
    "setType": "promo",
    "releasedAt": "2023-01-01",
    "parentSetCode": null
  },
  {
    "code": "pw24",
    "name": "Wizards Play Network 2024",
    "setType": "promo",
    "releasedAt": "2024-01-01",
    "parentSetCode": null
  },
  {
    "code": "pw25",
    "name": "Wizards Play Network 2025",
    "setType": "promo",
    "releasedAt": "2025-01-01",
    "parentSetCode": null
  },
  {
    "code": "pw26",
    "name": "Wizards Play Network 2026",
    "setType": "promo",
    "releasedAt": "2026-01-01",
    "parentSetCode": null
  },
  {
    "code": "pwar",
    "name": "War of the Spark Promos",
    "setType": "promo",
    "releasedAt": "2019-05-03",
    "parentSetCode": "war"
  },
  {
    "code": "pwcs",
    "name": "Planeswalker Championship Promos",
    "setType": "promo",
    "releasedAt": "2019-10-01",
    "parentSetCode": null
  },
  {
    "code": "pwoe",
    "name": "Wilds of Eldraine Promos",
    "setType": "promo",
    "releasedAt": "2023-09-08",
    "parentSetCode": "woe"
  },
  {
    "code": "pwor",
    "name": "World Championship Promos",
    "setType": "promo",
    "releasedAt": "1999-08-04",
    "parentSetCode": null
  },
  {
    "code": "pwos",
    "name": "Wizards of the Coast Online Store",
    "setType": "promo",
    "releasedAt": "1999-09-04",
    "parentSetCode": null
  },
  {
    "code": "pwwk",
    "name": "Worldwake Promos",
    "setType": "promo",
    "releasedAt": "2010-02-05",
    "parentSetCode": "wwk"
  },
  {
    "code": "pxln",
    "name": "Ixalan Promos",
    "setType": "promo",
    "releasedAt": "2017-09-29",
    "parentSetCode": "xln"
  },
  {
    "code": "pxtc",
    "name": "XLN Treasure Chest",
    "setType": "promo",
    "releasedAt": "2017-11-24",
    "parentSetCode": "xln"
  },
  {
    "code": "pza",
    "name": "Teenage Mutant Ninja Turtles Source Material",
    "setType": "masterpiece",
    "releasedAt": "2026-03-06",
    "parentSetCode": "tmt"
  },
  {
    "code": "pzen",
    "name": "Zendikar Promos",
    "setType": "promo",
    "releasedAt": "2009-10-02",
    "parentSetCode": "zen"
  },
  {
    "code": "pznr",
    "name": "Zendikar Rising Promos",
    "setType": "promo",
    "releasedAt": "2020-09-25",
    "parentSetCode": "znr"
  },
  {
    "code": "q06",
    "name": "Pioneer Challenger Decks 2021",
    "setType": "box",
    "releasedAt": "2021-10-15",
    "parentSetCode": null
  },
  {
    "code": "q07",
    "name": "Challenger Decks 2022",
    "setType": "box",
    "releasedAt": "2022-04-01",
    "parentSetCode": null
  },
  {
    "code": "rav",
    "name": "Ravnica: City of Guilds",
    "setType": "expansion",
    "releasedAt": "2005-10-07",
    "parentSetCode": null
  },
  {
    "code": "ren",
    "name": "Renaissance",
    "setType": "masters",
    "releasedAt": "1995-08-01",
    "parentSetCode": null
  },
  {
    "code": "rex",
    "name": "Jurassic World Collection",
    "setType": "eternal",
    "releasedAt": "2023-11-17",
    "parentSetCode": "lci"
  },
  {
    "code": "rfin",
    "name": "Final Fantasy Regional Promos",
    "setType": "promo",
    "releasedAt": "2025-06-13",
    "parentSetCode": "fin"
  },
  {
    "code": "rin",
    "name": "Rinascimento",
    "setType": "masters",
    "releasedAt": "1995-08-01",
    "parentSetCode": null
  },
  {
    "code": "rix",
    "name": "Rivals of Ixalan",
    "setType": "expansion",
    "releasedAt": "2018-01-19",
    "parentSetCode": null
  },
  {
    "code": "rna",
    "name": "Ravnica Allegiance",
    "setType": "expansion",
    "releasedAt": "2019-01-25",
    "parentSetCode": null
  },
  {
    "code": "roe",
    "name": "Rise of the Eldrazi",
    "setType": "expansion",
    "releasedAt": "2010-04-23",
    "parentSetCode": null
  },
  {
    "code": "rqs",
    "name": "Rivals Quick Start Set",
    "setType": "box",
    "releasedAt": "1996-07-01",
    "parentSetCode": null
  },
  {
    "code": "rtr",
    "name": "Return to Ravnica",
    "setType": "expansion",
    "releasedAt": "2012-10-05",
    "parentSetCode": null
  },
  {
    "code": "rvr",
    "name": "Ravnica Remastered",
    "setType": "masters",
    "releasedAt": "2024-01-12",
    "parentSetCode": null
  },
  {
    "code": "s00",
    "name": "Starter 2000",
    "setType": "starter",
    "releasedAt": "2000-04-01",
    "parentSetCode": null
  },
  {
    "code": "s99",
    "name": "Starter 1999",
    "setType": "starter",
    "releasedAt": "1999-07-01",
    "parentSetCode": null
  },
  {
    "code": "scd",
    "name": "Starter Commander Decks",
    "setType": "commander",
    "releasedAt": "2022-12-02",
    "parentSetCode": null
  },
  {
    "code": "scg",
    "name": "Scourge",
    "setType": "expansion",
    "releasedAt": "2003-05-26",
    "parentSetCode": null
  },
  {
    "code": "sch",
    "name": "Store Championships",
    "setType": "promo",
    "releasedAt": "2022-07-09",
    "parentSetCode": null
  },
  {
    "code": "sds",
    "name": "Stardates",
    "setType": "masterpiece",
    "releasedAt": "2026-11-13",
    "parentSetCode": "trk"
  },
  {
    "code": "shm",
    "name": "Shadowmoor",
    "setType": "expansion",
    "releasedAt": "2008-05-02",
    "parentSetCode": null
  },
  {
    "code": "slc",
    "name": "Secret Lair Countdown",
    "setType": "box",
    "releasedAt": "2022-11-01",
    "parentSetCode": "sld"
  },
  {
    "code": "sld",
    "name": "Secret Lair Drop",
    "setType": "box",
    "releasedAt": "2019-12-02",
    "parentSetCode": null
  },
  {
    "code": "slp",
    "name": "Secret Lair Promo",
    "setType": "promo",
    "releasedAt": "2023-02-17",
    "parentSetCode": "sld"
  },
  {
    "code": "slu",
    "name": "Secret Lair: Ultimate Edition",
    "setType": "box",
    "releasedAt": "2020-05-29",
    "parentSetCode": "sld"
  },
  {
    "code": "slx",
    "name": "Universes Within",
    "setType": "masters",
    "releasedAt": "2022-03-03",
    "parentSetCode": "sld"
  },
  {
    "code": "snc",
    "name": "Streets of New Capenna",
    "setType": "expansion",
    "releasedAt": "2022-04-29",
    "parentSetCode": null
  },
  {
    "code": "soa",
    "name": "Secrets of Strixhaven Mystical Archive",
    "setType": "masterpiece",
    "releasedAt": "2026-04-24",
    "parentSetCode": "sos"
  },
  {
    "code": "soc",
    "name": "Secrets of Strixhaven Commander",
    "setType": "commander",
    "releasedAt": "2026-04-24",
    "parentSetCode": "sos"
  },
  {
    "code": "soi",
    "name": "Shadows over Innistrad",
    "setType": "expansion",
    "releasedAt": "2016-04-08",
    "parentSetCode": null
  },
  {
    "code": "sok",
    "name": "Saviors of Kamigawa",
    "setType": "expansion",
    "releasedAt": "2005-06-03",
    "parentSetCode": null
  },
  {
    "code": "som",
    "name": "Scars of Mirrodin",
    "setType": "expansion",
    "releasedAt": "2010-10-01",
    "parentSetCode": null
  },
  {
    "code": "sos",
    "name": "Secrets of Strixhaven",
    "setType": "expansion",
    "releasedAt": "2026-04-24",
    "parentSetCode": null
  },
  {
    "code": "spe",
    "name": "Marvel's Spider-Man Eternal",
    "setType": "eternal",
    "releasedAt": "2025-09-26",
    "parentSetCode": "spm"
  },
  {
    "code": "spg",
    "name": "Special Guests",
    "setType": "masterpiece",
    "releasedAt": "2023-11-17",
    "parentSetCode": null
  },
  {
    "code": "spm",
    "name": "Marvel's Spider-Man",
    "setType": "expansion",
    "releasedAt": "2025-09-26",
    "parentSetCode": null
  },
  {
    "code": "ss1",
    "name": "Signature Spellbook: Jace",
    "setType": "spellbook",
    "releasedAt": "2018-06-15",
    "parentSetCode": null
  },
  {
    "code": "ss2",
    "name": "Signature Spellbook: Gideon",
    "setType": "spellbook",
    "releasedAt": "2019-06-28",
    "parentSetCode": null
  },
  {
    "code": "ss3",
    "name": "Signature Spellbook: Chandra",
    "setType": "spellbook",
    "releasedAt": "2020-06-26",
    "parentSetCode": null
  },
  {
    "code": "sta",
    "name": "Strixhaven Mystical Archive",
    "setType": "masterpiece",
    "releasedAt": "2021-04-23",
    "parentSetCode": "stx"
  },
  {
    "code": "sth",
    "name": "Stronghold",
    "setType": "expansion",
    "releasedAt": "1998-03-02",
    "parentSetCode": null
  },
  {
    "code": "stx",
    "name": "Strixhaven: School of Mages",
    "setType": "expansion",
    "releasedAt": "2021-04-23",
    "parentSetCode": null
  },
  {
    "code": "sum",
    "name": "Summer Magic / Edgar",
    "setType": "core",
    "releasedAt": "1994-06-21",
    "parentSetCode": null
  },
  {
    "code": "sunf",
    "name": "Unfinity Sticker Sheets",
    "setType": "funny",
    "releasedAt": "2022-10-07",
    "parentSetCode": "unf"
  },
  {
    "code": "tdc",
    "name": "Tarkir: Dragonstorm Commander",
    "setType": "commander",
    "releasedAt": "2025-04-11",
    "parentSetCode": "tdm"
  },
  {
    "code": "tdm",
    "name": "Tarkir: Dragonstorm",
    "setType": "expansion",
    "releasedAt": "2025-04-11",
    "parentSetCode": null
  },
  {
    "code": "thb",
    "name": "Theros Beyond Death",
    "setType": "expansion",
    "releasedAt": "2020-01-24",
    "parentSetCode": null
  },
  {
    "code": "ths",
    "name": "Theros",
    "setType": "expansion",
    "releasedAt": "2013-09-27",
    "parentSetCode": null
  },
  {
    "code": "tla",
    "name": "Avatar: The Last Airbender",
    "setType": "expansion",
    "releasedAt": "2025-11-21",
    "parentSetCode": null
  },
  {
    "code": "tle",
    "name": "Avatar: The Last Airbender Eternal",
    "setType": "eternal",
    "releasedAt": "2025-11-21",
    "parentSetCode": "tla"
  },
  {
    "code": "tmc",
    "name": "Teenage Mutant Ninja Turtles Eternal",
    "setType": "eternal",
    "releasedAt": "2026-03-06",
    "parentSetCode": "tmt"
  },
  {
    "code": "tmp",
    "name": "Tempest",
    "setType": "expansion",
    "releasedAt": "1997-10-14",
    "parentSetCode": null
  },
  {
    "code": "tmt",
    "name": "Teenage Mutant Ninja Turtles",
    "setType": "expansion",
    "releasedAt": "2026-03-06",
    "parentSetCode": null
  },
  {
    "code": "tor",
    "name": "Torment",
    "setType": "expansion",
    "releasedAt": "2002-02-04",
    "parentSetCode": null
  },
  {
    "code": "trc",
    "name": "Star Trek Commander",
    "setType": "commander",
    "releasedAt": "2026-11-13",
    "parentSetCode": "trk"
  },
  {
    "code": "trk",
    "name": "Star Trek",
    "setType": "expansion",
    "releasedAt": "2026-11-13",
    "parentSetCode": null
  },
  {
    "code": "tsb",
    "name": "Time Spiral Timeshifted",
    "setType": "expansion",
    "releasedAt": "2006-10-06",
    "parentSetCode": "tsp"
  },
  {
    "code": "tsp",
    "name": "Time Spiral",
    "setType": "expansion",
    "releasedAt": "2006-10-06",
    "parentSetCode": null
  },
  {
    "code": "tsr",
    "name": "Time Spiral Remastered",
    "setType": "masters",
    "releasedAt": "2021-03-19",
    "parentSetCode": null
  },
  {
    "code": "uds",
    "name": "Urza's Destiny",
    "setType": "expansion",
    "releasedAt": "1999-06-07",
    "parentSetCode": null
  },
  {
    "code": "ugin",
    "name": "Ugin's Fate",
    "setType": "promo",
    "releasedAt": "2015-01-17",
    "parentSetCode": "frf"
  },
  {
    "code": "ugl",
    "name": "Unglued",
    "setType": "funny",
    "releasedAt": "1998-08-11",
    "parentSetCode": null
  },
  {
    "code": "ulg",
    "name": "Urza's Legacy",
    "setType": "expansion",
    "releasedAt": "1999-02-15",
    "parentSetCode": null
  },
  {
    "code": "ulst",
    "name": "The List (Unfinity Foil Edition)",
    "setType": "funny",
    "releasedAt": "2022-10-07",
    "parentSetCode": "plst"
  },
  {
    "code": "uma",
    "name": "Ultimate Masters",
    "setType": "masters",
    "releasedAt": "2018-12-07",
    "parentSetCode": null
  },
  {
    "code": "und",
    "name": "Unsanctioned",
    "setType": "funny",
    "releasedAt": "2020-02-29",
    "parentSetCode": null
  },
  {
    "code": "unf",
    "name": "Unfinity",
    "setType": "funny",
    "releasedAt": "2022-10-07",
    "parentSetCode": null
  },
  {
    "code": "unh",
    "name": "Unhinged",
    "setType": "funny",
    "releasedAt": "2004-11-19",
    "parentSetCode": null
  },
  {
    "code": "unk",
    "name": "Unknown Event",
    "setType": "funny",
    "releasedAt": "2023-02-15",
    "parentSetCode": null
  },
  {
    "code": "usg",
    "name": "Urza's Saga",
    "setType": "expansion",
    "releasedAt": "1998-10-12",
    "parentSetCode": null
  },
  {
    "code": "ust",
    "name": "Unstable",
    "setType": "funny",
    "releasedAt": "2017-12-08",
    "parentSetCode": null
  },
  {
    "code": "v09",
    "name": "From the Vault: Exiled",
    "setType": "from_the_vault",
    "releasedAt": "2009-08-28",
    "parentSetCode": null
  },
  {
    "code": "v10",
    "name": "From the Vault: Relics",
    "setType": "from_the_vault",
    "releasedAt": "2010-08-27",
    "parentSetCode": null
  },
  {
    "code": "v11",
    "name": "From the Vault: Legends",
    "setType": "from_the_vault",
    "releasedAt": "2011-08-26",
    "parentSetCode": null
  },
  {
    "code": "v12",
    "name": "From the Vault: Realms",
    "setType": "from_the_vault",
    "releasedAt": "2012-08-31",
    "parentSetCode": null
  },
  {
    "code": "v13",
    "name": "From the Vault: Twenty",
    "setType": "from_the_vault",
    "releasedAt": "2013-08-23",
    "parentSetCode": null
  },
  {
    "code": "v14",
    "name": "From the Vault: Annihilation",
    "setType": "from_the_vault",
    "releasedAt": "2014-08-22",
    "parentSetCode": null
  },
  {
    "code": "v15",
    "name": "From the Vault: Angels",
    "setType": "from_the_vault",
    "releasedAt": "2015-08-21",
    "parentSetCode": null
  },
  {
    "code": "v16",
    "name": "From the Vault: Lore",
    "setType": "from_the_vault",
    "releasedAt": "2016-08-19",
    "parentSetCode": null
  },
  {
    "code": "v17",
    "name": "From the Vault: Transform",
    "setType": "from_the_vault",
    "releasedAt": "2017-11-24",
    "parentSetCode": null
  },
  {
    "code": "vis",
    "name": "Visions",
    "setType": "expansion",
    "releasedAt": "1997-02-03",
    "parentSetCode": null
  },
  {
    "code": "voc",
    "name": "Crimson Vow Commander",
    "setType": "commander",
    "releasedAt": "2021-11-19",
    "parentSetCode": "vow"
  },
  {
    "code": "vow",
    "name": "Innistrad: Crimson Vow",
    "setType": "expansion",
    "releasedAt": "2021-11-19",
    "parentSetCode": null
  },
  {
    "code": "w16",
    "name": "Welcome Deck 2016",
    "setType": "starter",
    "releasedAt": "2016-04-08",
    "parentSetCode": null
  },
  {
    "code": "w17",
    "name": "Welcome Deck 2017",
    "setType": "starter",
    "releasedAt": "2017-04-15",
    "parentSetCode": null
  },
  {
    "code": "war",
    "name": "War of the Spark",
    "setType": "expansion",
    "releasedAt": "2019-05-03",
    "parentSetCode": null
  },
  {
    "code": "who",
    "name": "Doctor Who",
    "setType": "commander",
    "releasedAt": "2023-10-13",
    "parentSetCode": null
  },
  {
    "code": "wmc",
    "name": "World Magic Cup Qualifiers",
    "setType": "promo",
    "releasedAt": "2013-04-06",
    "parentSetCode": null
  },
  {
    "code": "woc",
    "name": "Wilds of Eldraine Commander",
    "setType": "commander",
    "releasedAt": "2023-09-08",
    "parentSetCode": "woe"
  },
  {
    "code": "woe",
    "name": "Wilds of Eldraine",
    "setType": "expansion",
    "releasedAt": "2023-09-08",
    "parentSetCode": null
  },
  {
    "code": "wot",
    "name": "Wilds of Eldraine: Enchanting Tales",
    "setType": "masterpiece",
    "releasedAt": "2023-09-08",
    "parentSetCode": "woe"
  },
  {
    "code": "wth",
    "name": "Weatherlight",
    "setType": "expansion",
    "releasedAt": "1997-06-09",
    "parentSetCode": null
  },
  {
    "code": "wwk",
    "name": "Worldwake",
    "setType": "expansion",
    "releasedAt": "2010-02-05",
    "parentSetCode": null
  },
  {
    "code": "xln",
    "name": "Ixalan",
    "setType": "expansion",
    "releasedAt": "2017-09-29",
    "parentSetCode": null
  },
  {
    "code": "zen",
    "name": "Zendikar",
    "setType": "expansion",
    "releasedAt": "2009-10-02",
    "parentSetCode": null
  },
  {
    "code": "znc",
    "name": "Zendikar Rising Commander",
    "setType": "commander",
    "releasedAt": "2020-09-25",
    "parentSetCode": "znr"
  },
  {
    "code": "zne",
    "name": "Zendikar Rising Expeditions",
    "setType": "masterpiece",
    "releasedAt": "2020-09-25",
    "parentSetCode": "znr"
  },
  {
    "code": "znr",
    "name": "Zendikar Rising",
    "setType": "expansion",
    "releasedAt": "2020-09-25",
    "parentSetCode": null
  }
];

export const SCRYFALL_SET_CODES: ReadonlySet<string> = new Set(
  SCRYFALL_SETS.map((set) => set.code),
);
