// AUTO-GENERATED by scripts/generate-subtype-vocabulary.mjs — do not edit by hand.
// Source: https://api.scryfall.com/catalog/{creature,planeswalker,land,artifact,enchantment,spell}-types
// Regenerate with: node scripts/generate-subtype-vocabulary.mjs

export interface ScryfallSubtypeEntry {
  /** Canonical subtype as printed on cards (e.g. "Monkey"). */
  subtype: string;
  /** Lowercased lookup key (e.g. "monkey"). */
  slug: string;
  /** Which type catalogs the subtype appears in. */
  categories: readonly string[];
}

export const SCRYFALL_SUBTYPES: readonly ScryfallSubtypeEntry[] = [
  {
    "subtype": "Abian",
    "slug": "abian",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Advisor",
    "slug": "advisor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Aetherborn",
    "slug": "aetherborn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ajani",
    "slug": "ajani",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Alien",
    "slug": "alien",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ally",
    "slug": "ally",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Aminatou",
    "slug": "aminatou",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Andorian",
    "slug": "andorian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Angel",
    "slug": "angel",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Angrath",
    "slug": "angrath",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Antelope",
    "slug": "antelope",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ape",
    "slug": "ape",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Archer",
    "slug": "archer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Archon",
    "slug": "archon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Arlinn",
    "slug": "arlinn",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Armadillo",
    "slug": "armadillo",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Army",
    "slug": "army",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Artificer",
    "slug": "artificer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Arzakon",
    "slug": "arzakon",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ashiok",
    "slug": "ashiok",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Assassin",
    "slug": "assassin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Assembly-Worker",
    "slug": "assembly-worker",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Astartes",
    "slug": "astartes",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Atog",
    "slug": "atog",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Aurochs",
    "slug": "aurochs",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Automaton",
    "slug": "automaton",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Avatar",
    "slug": "avatar",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Azra",
    "slug": "azra",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "B.O.B.",
    "slug": "b.o.b.",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Badger",
    "slug": "badger",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bahamut",
    "slug": "bahamut",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Balloon",
    "slug": "balloon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Barbarian",
    "slug": "barbarian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bard",
    "slug": "bard",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Basilisk",
    "slug": "basilisk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Basri",
    "slug": "basri",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Bat",
    "slug": "bat",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bear",
    "slug": "bear",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Beast",
    "slug": "beast",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Beaver",
    "slug": "beaver",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Beeble",
    "slug": "beeble",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Beholder",
    "slug": "beholder",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Berserker",
    "slug": "berserker",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bird",
    "slug": "bird",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bison",
    "slug": "bison",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Blinkmoth",
    "slug": "blinkmoth",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Boar",
    "slug": "boar",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bobblehead",
    "slug": "bobblehead",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Bolas",
    "slug": "bolas",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Book",
    "slug": "book",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Borg",
    "slug": "borg",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Brainiac",
    "slug": "brainiac",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Bringer",
    "slug": "bringer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Brushwagg",
    "slug": "brushwagg",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "C'tan",
    "slug": "c'tan",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Caitian",
    "slug": "caitian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Calix",
    "slug": "calix",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Camarid",
    "slug": "camarid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Camel",
    "slug": "camel",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Capybara",
    "slug": "capybara",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Caribou",
    "slug": "caribou",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Carrier",
    "slug": "carrier",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cartouche",
    "slug": "cartouche",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Case",
    "slug": "case",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Cat",
    "slug": "cat",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Centaur",
    "slug": "centaur",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Chandra",
    "slug": "chandra",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Chicken",
    "slug": "chicken",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Child",
    "slug": "child",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Chimera",
    "slug": "chimera",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Chorus",
    "slug": "chorus",
    "categories": [
      "spell"
    ]
  },
  {
    "subtype": "Citizen",
    "slug": "citizen",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cleric",
    "slug": "cleric",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cloud",
    "slug": "cloud",
    "categories": [
      "land"
    ]
  },
  {
    "subtype": "Clown",
    "slug": "clown",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cockatrice",
    "slug": "cockatrice",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Comet",
    "slug": "comet",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Construct",
    "slug": "construct",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Coward",
    "slug": "coward",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Coyote",
    "slug": "coyote",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Crab",
    "slug": "crab",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Crocodile",
    "slug": "crocodile",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Custodes",
    "slug": "custodes",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cyberman",
    "slug": "cyberman",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Cyclops",
    "slug": "cyclops",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dack",
    "slug": "dack",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dakkon",
    "slug": "dakkon",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dalek",
    "slug": "dalek",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Daretti",
    "slug": "daretti",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dauthi",
    "slug": "dauthi",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Davriel",
    "slug": "davriel",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Deb",
    "slug": "deb",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dellian",
    "slug": "dellian",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Demigod",
    "slug": "demigod",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Demon",
    "slug": "demon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Deserter",
    "slug": "deserter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Detective",
    "slug": "detective",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Devil",
    "slug": "devil",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dihada",
    "slug": "dihada",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dinosaur",
    "slug": "dinosaur",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Djinn",
    "slug": "djinn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Doctor",
    "slug": "doctor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dog",
    "slug": "dog",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Domri",
    "slug": "domri",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dovin",
    "slug": "dovin",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dragon",
    "slug": "dragon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Drake",
    "slug": "drake",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dreadnought",
    "slug": "dreadnought",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Drix",
    "slug": "drix",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Drone",
    "slug": "drone",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Druid",
    "slug": "druid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dryad",
    "slug": "dryad",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Duck",
    "slug": "duck",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dungeon",
    "slug": "dungeon",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Dwarf",
    "slug": "dwarf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Dyfed",
    "slug": "dyfed",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Echidna",
    "slug": "echidna",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Efreet",
    "slug": "efreet",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Elder",
    "slug": "elder",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Eldrazi",
    "slug": "eldrazi",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Elemental",
    "slug": "elemental",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Elephant",
    "slug": "elephant",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Elf",
    "slug": "elf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Elk",
    "slug": "elk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ellywick",
    "slug": "ellywick",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Elminster",
    "slug": "elminster",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Elspeth",
    "slug": "elspeth",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Employee",
    "slug": "employee",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ersta",
    "slug": "ersta",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Estrid",
    "slug": "estrid",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Eternal",
    "slug": "eternal",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Eye",
    "slug": "eye",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Faerie",
    "slug": "faerie",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Feroz",
    "slug": "feroz",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ferret",
    "slug": "ferret",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Fish",
    "slug": "fish",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Flagbearer",
    "slug": "flagbearer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Fortification",
    "slug": "fortification",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Fox",
    "slug": "fox",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Fractal",
    "slug": "fractal",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Freyalise",
    "slug": "freyalise",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Frog",
    "slug": "frog",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Fungus",
    "slug": "fungus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gamer",
    "slug": "gamer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gamma",
    "slug": "gamma",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gargoyle",
    "slug": "gargoyle",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Garruk",
    "slug": "garruk",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Germ",
    "slug": "germ",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gideon",
    "slug": "gideon",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Giraffe",
    "slug": "giraffe",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gith",
    "slug": "gith",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Glimmer",
    "slug": "glimmer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gnoll",
    "slug": "gnoll",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gnome",
    "slug": "gnome",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Goat",
    "slug": "goat",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Goblin",
    "slug": "goblin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "God",
    "slug": "god",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Golem",
    "slug": "golem",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gorgon",
    "slug": "gorgon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Gorn",
    "slug": "gorn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Graveborn",
    "slug": "graveborn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Greensleeves",
    "slug": "greensleeves",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Gremlin",
    "slug": "gremlin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Griffin",
    "slug": "griffin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Grist",
    "slug": "grist",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Guest",
    "slug": "guest",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Guff",
    "slug": "guff",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Hag",
    "slug": "hag",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Halfling",
    "slug": "halfling",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hamster",
    "slug": "hamster",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Harpy",
    "slug": "harpy",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Head",
    "slug": "head",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hedgehog",
    "slug": "hedgehog",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hellion",
    "slug": "hellion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hero",
    "slug": "hero",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hippo",
    "slug": "hippo",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hippogriff",
    "slug": "hippogriff",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Homarid",
    "slug": "homarid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Homunculus",
    "slug": "homunculus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Horror",
    "slug": "horror",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Horse",
    "slug": "horse",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Huatli",
    "slug": "huatli",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Human",
    "slug": "human",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hydra",
    "slug": "hydra",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Hyena",
    "slug": "hyena",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Illusion",
    "slug": "illusion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Imp",
    "slug": "imp",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Incarnation",
    "slug": "incarnation",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Infinity",
    "slug": "infinity",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Inhuman",
    "slug": "inhuman",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Inkling",
    "slug": "inkling",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Inquisitor",
    "slug": "inquisitor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Insect",
    "slug": "insect",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Inzerva",
    "slug": "inzerva",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Jace",
    "slug": "jace",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Jackal",
    "slug": "jackal",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Jared",
    "slug": "jared",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Jaya",
    "slug": "jaya",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Jellyfish",
    "slug": "jellyfish",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Jeska",
    "slug": "jeska",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Juggernaut",
    "slug": "juggernaut",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Junk",
    "slug": "junk",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Kaito",
    "slug": "kaito",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kangaroo",
    "slug": "kangaroo",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Karn",
    "slug": "karn",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kasmina",
    "slug": "kasmina",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kavu",
    "slug": "kavu",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kaya",
    "slug": "kaya",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kelpien",
    "slug": "kelpien",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kiora",
    "slug": "kiora",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kirin",
    "slug": "kirin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kithkin",
    "slug": "kithkin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Klingon",
    "slug": "klingon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Knight",
    "slug": "knight",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kobold",
    "slug": "kobold",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kor",
    "slug": "kor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Koth",
    "slug": "koth",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Kraken",
    "slug": "kraken",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Kree",
    "slug": "kree",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lamia",
    "slug": "lamia",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lammasu",
    "slug": "lammasu",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lanthanite",
    "slug": "lanthanite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Leech",
    "slug": "leech",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lemur",
    "slug": "lemur",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Leviathan",
    "slug": "leviathan",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lhurgoyf",
    "slug": "lhurgoyf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Licid",
    "slug": "licid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Liliana",
    "slug": "liliana",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Lizard",
    "slug": "lizard",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Llama",
    "slug": "llama",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lobster",
    "slug": "lobster",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Lolth",
    "slug": "lolth",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Lukka",
    "slug": "lukka",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Luxior",
    "slug": "luxior",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Manticore",
    "slug": "manticore",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Master",
    "slug": "master",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Masticore",
    "slug": "masticore",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mercenary",
    "slug": "mercenary",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Merfolk",
    "slug": "merfolk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Metathran",
    "slug": "metathran",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Minion",
    "slug": "minion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Minotaur",
    "slug": "minotaur",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Minsc",
    "slug": "minsc",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Mite",
    "slug": "mite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mole",
    "slug": "mole",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Monger",
    "slug": "monger",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mongoose",
    "slug": "mongoose",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Monk",
    "slug": "monk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Monkey",
    "slug": "monkey",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Monopoly",
    "slug": "monopoly",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Moogle",
    "slug": "moogle",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Moonfolk",
    "slug": "moonfolk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mordenkainen",
    "slug": "mordenkainen",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Mount",
    "slug": "mount",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mouse",
    "slug": "mouse",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mutant",
    "slug": "mutant",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Myr",
    "slug": "myr",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Mystic",
    "slug": "mystic",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Naga",
    "slug": "naga",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nahiri",
    "slug": "nahiri",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Narset",
    "slug": "narset",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Nautilus",
    "slug": "nautilus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Necron",
    "slug": "necron",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nephilim",
    "slug": "nephilim",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nightmare",
    "slug": "nightmare",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nightstalker",
    "slug": "nightstalker",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Niko",
    "slug": "niko",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ninja",
    "slug": "ninja",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nissa",
    "slug": "nissa",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Nixilis",
    "slug": "nixilis",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Noble",
    "slug": "noble",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Noggle",
    "slug": "noggle",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nomad",
    "slug": "nomad",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Nymph",
    "slug": "nymph",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Octopus",
    "slug": "octopus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Officer",
    "slug": "officer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ogre",
    "slug": "ogre",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Oko",
    "slug": "oko",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ooze",
    "slug": "ooze",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Orb",
    "slug": "orb",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Orc",
    "slug": "orc",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Orgg",
    "slug": "orgg",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Orion",
    "slug": "orion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Otter",
    "slug": "otter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ouphe",
    "slug": "ouphe",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ox",
    "slug": "ox",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Oyster",
    "slug": "oyster",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pangolin",
    "slug": "pangolin",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Peasant",
    "slug": "peasant",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pegasus",
    "slug": "pegasus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pentavite",
    "slug": "pentavite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Performer",
    "slug": "performer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pest",
    "slug": "pest",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Phelddagrif",
    "slug": "phelddagrif",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Phoenix",
    "slug": "phoenix",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Phyrexian",
    "slug": "phyrexian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pilot",
    "slug": "pilot",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pincher",
    "slug": "pincher",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Pirate",
    "slug": "pirate",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Plan",
    "slug": "plan",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Planet",
    "slug": "planet",
    "categories": [
      "land"
    ]
  },
  {
    "subtype": "Plant",
    "slug": "plant",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Platypus",
    "slug": "platypus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Porcupine",
    "slug": "porcupine",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Possum",
    "slug": "possum",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Praetor",
    "slug": "praetor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Primarch",
    "slug": "primarch",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Prism",
    "slug": "prism",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Processor",
    "slug": "processor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Q",
    "slug": "q",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Qu",
    "slug": "qu",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Quintorius",
    "slug": "quintorius",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Rabbit",
    "slug": "rabbit",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Raccoon",
    "slug": "raccoon",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Ral",
    "slug": "ral",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ranger",
    "slug": "ranger",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rat",
    "slug": "rat",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rebel",
    "slug": "rebel",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Reflection",
    "slug": "reflection",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Reveler",
    "slug": "reveler",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rhino",
    "slug": "rhino",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rigger",
    "slug": "rigger",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Robot",
    "slug": "robot",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rogue",
    "slug": "rogue",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Room",
    "slug": "room",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Rowan",
    "slug": "rowan",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Rukh",
    "slug": "rukh",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Rune",
    "slug": "rune",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Sable",
    "slug": "sable",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Saheeli",
    "slug": "saheeli",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Salamander",
    "slug": "salamander",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Samurai",
    "slug": "samurai",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Samut",
    "slug": "samut",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Sand",
    "slug": "sand",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Saproling",
    "slug": "saproling",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sarkhan",
    "slug": "sarkhan",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Satyr",
    "slug": "satyr",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Scarecrow",
    "slug": "scarecrow",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Scientist",
    "slug": "scientist",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Scion",
    "slug": "scion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Scorpion",
    "slug": "scorpion",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Scout",
    "slug": "scout",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sculpture",
    "slug": "sculpture",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Seal",
    "slug": "seal",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Serf",
    "slug": "serf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Serpent",
    "slug": "serpent",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Serra",
    "slug": "serra",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Servo",
    "slug": "servo",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shade",
    "slug": "shade",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shaman",
    "slug": "shaman",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shapeshifter",
    "slug": "shapeshifter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shark",
    "slug": "shark",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sheep",
    "slug": "sheep",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shi'ar",
    "slug": "shi'ar",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Shrine",
    "slug": "shrine",
    "categories": [
      "enchantment"
    ]
  },
  {
    "subtype": "Sifa",
    "slug": "sifa",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Siren",
    "slug": "siren",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sivitri",
    "slug": "sivitri",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Skeleton",
    "slug": "skeleton",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Skrull",
    "slug": "skrull",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Skunk",
    "slug": "skunk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Slith",
    "slug": "slith",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sliver",
    "slug": "sliver",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sloth",
    "slug": "sloth",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Slug",
    "slug": "slug",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Snail",
    "slug": "snail",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Snake",
    "slug": "snake",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Soldier",
    "slug": "soldier",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Soltari",
    "slug": "soltari",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sorcerer",
    "slug": "sorcerer",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sorin",
    "slug": "sorin",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Spacecraft",
    "slug": "spacecraft",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Spawn",
    "slug": "spawn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Specter",
    "slug": "specter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Spellshaper",
    "slug": "spellshaper",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sphinx",
    "slug": "sphinx",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Spider",
    "slug": "spider",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Spike",
    "slug": "spike",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Spirit",
    "slug": "spirit",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Splinter",
    "slug": "splinter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Sponge",
    "slug": "sponge",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Spy",
    "slug": "spy",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Squid",
    "slug": "squid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Squirrel",
    "slug": "squirrel",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Starfish",
    "slug": "starfish",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Stone",
    "slug": "stone",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Surrakar",
    "slug": "surrakar",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Survivor",
    "slug": "survivor",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Svega",
    "slug": "svega",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Symbiote",
    "slug": "symbiote",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Synth",
    "slug": "synth",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Szat",
    "slug": "szat",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Talosian",
    "slug": "talosian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tamiyo",
    "slug": "tamiyo",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Tasha",
    "slug": "tasha",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Teddy",
    "slug": "teddy",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Teferi",
    "slug": "teferi",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Tellarite",
    "slug": "tellarite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tentacle",
    "slug": "tentacle",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Terminus",
    "slug": "terminus",
    "categories": [
      "artifact"
    ]
  },
  {
    "subtype": "Tetravite",
    "slug": "tetravite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Teyo",
    "slug": "teyo",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Tezzeret",
    "slug": "tezzeret",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Thalakos",
    "slug": "thalakos",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tholian",
    "slug": "tholian",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Thomil",
    "slug": "thomil",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Thopter",
    "slug": "thopter",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Thrull",
    "slug": "thrull",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tibalt",
    "slug": "tibalt",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Tiefling",
    "slug": "tiefling",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Time Lord",
    "slug": "time lord",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tosk",
    "slug": "tosk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Town",
    "slug": "town",
    "categories": [
      "land"
    ]
  },
  {
    "subtype": "Toy",
    "slug": "toy",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Treefolk",
    "slug": "treefolk",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Trilobite",
    "slug": "trilobite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Triskelavite",
    "slug": "triskelavite",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Troll",
    "slug": "troll",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Turtle",
    "slug": "turtle",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tyranid",
    "slug": "tyranid",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Tyvar",
    "slug": "tyvar",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Ugin",
    "slug": "ugin",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Unicorn",
    "slug": "unicorn",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Urza",
    "slug": "urza",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Urza's",
    "slug": "urza's",
    "categories": [
      "land"
    ]
  },
  {
    "subtype": "Urzan",
    "slug": "urzan",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Utrom",
    "slug": "utrom",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Vampire",
    "slug": "vampire",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Varmint",
    "slug": "varmint",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Vedalken",
    "slug": "vedalken",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Venser",
    "slug": "venser",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Villain",
    "slug": "villain",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Vivien",
    "slug": "vivien",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Volver",
    "slug": "volver",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Vorta",
    "slug": "vorta",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Vraska",
    "slug": "vraska",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Vronos",
    "slug": "vronos",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Vulcan",
    "slug": "vulcan",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Walrus",
    "slug": "walrus",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Wanderer",
    "slug": "wanderer",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Warlock",
    "slug": "warlock",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Warrior",
    "slug": "warrior",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Weasel",
    "slug": "weasel",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Weird",
    "slug": "weird",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Werewolf",
    "slug": "werewolf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Whale",
    "slug": "whale",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Will",
    "slug": "will",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Windgrace",
    "slug": "windgrace",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Wizard",
    "slug": "wizard",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Wolf",
    "slug": "wolf",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Wolverine",
    "slug": "wolverine",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Wombat",
    "slug": "wombat",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Worm",
    "slug": "worm",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Worzel",
    "slug": "worzel",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Wraith",
    "slug": "wraith",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Wrenn",
    "slug": "wrenn",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Wurm",
    "slug": "wurm",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Xenagos",
    "slug": "xenagos",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Xindi",
    "slug": "xindi",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Yanggu",
    "slug": "yanggu",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Yanling",
    "slug": "yanling",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Yeti",
    "slug": "yeti",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Zariel",
    "slug": "zariel",
    "categories": [
      "planeswalker"
    ]
  },
  {
    "subtype": "Zombie",
    "slug": "zombie",
    "categories": [
      "creature"
    ]
  },
  {
    "subtype": "Zubera",
    "slug": "zubera",
    "categories": [
      "creature"
    ]
  }
] as const;

/** Fast lookup of every known subtype slug. */
export const SCRYFALL_SUBTYPE_SLUGS: ReadonlySet<string> = new Set(
  SCRYFALL_SUBTYPES.map((entry) => entry.slug),
);
