name: Bug report
description: Report a problem with OffMeta
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
      placeholder: 'Search results show no cards for valid query...'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Enter query ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
  - type: input
    id: node
    attributes:
      label: Node.js version
      description: Output of `node --version`.
      placeholder: v20.x
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant console or server logs.
      render: shell
