/**
 * Slang-to-Scryfall syntax mappings for common MTG terms.
 * These terms are often incorrectly generated by AI as invalid oracle tags (otag:).
 * Maps slang terms to valid Scryfall syntax.
 * @module mappings/slang-to-syntax
 */

export interface SlangMapping {
  /** Pattern to match the slang term */
  pattern: RegExp;
  /** Valid Scryfall syntax to use instead */
  syntax: string;
  /** Description for debugging/logs */
  description?: string;
}

/**
 * Slang terms that should NOT become otag: values.
 * The AI often incorrectly generates these as otag:counterspell, otag:aggro, etc.
 * This layer intercepts them and converts to valid Scryfall syntax.
 */
export const SLANG_TO_SYNTAX_MAP: SlangMapping[] = [
  // Counter magic (NOT otag:counterspell - that doesn't exist)
  {
    pattern: /\bcounterspells?\b/gi,
    syntax: 'otag:hard-counter',
    description: 'Counter target spell effects',
  },
  {
    pattern: /\bcounter ?magics?\b/gi,
    syntax: 'otag:hard-counter',
    description: 'Counter target spell effects',
  },
  {
    pattern: /\bspell counters?\b/gi,
    syntax: 'otag:hard-counter',
    description: 'Counter target spell effects',
  },

  // Aggro/Beatdown (NOT otag:aggro - that doesn't exist)
  {
    pattern: /\baggro\s+(?:creature|deck|cards?)?\b/gi,
    syntax: 't:creature mv<=3 pow>=2',
    description: 'Low-cost aggressive creatures',
  },
  {
    pattern: /\bbeatdown\b/gi,
    syntax: 't:creature pow>=3',
    description: 'High power creatures for attacking',
  },
  {
    pattern: /\bweenies?\b/gi,
    syntax: 't:creature mv<=2',
    description: 'Small cheap creatures',
  },

  // Sacrifice effects (NOT otag:sacrifice - use sacrifice-outlet)
  {
    pattern: /\bsac(?:rifice)?\s+outlets?\b/gi,
    syntax: 'otag:sacrifice-outlet',
    description: 'Cards that let you sacrifice permanents',
  },
  {
    pattern: /\bfree\s+sac(?:rifice)?\s+outlets?\b/gi,
    syntax: 'otag:free-sacrifice-outlet',
    description: 'Free sacrifice outlets (no mana cost)',
  },

  // Ramp variations (NOT otag:land-fetch - use land-ramp or ramp)
  {
    pattern: /\bland\s+fetching\b/gi,
    syntax: 'otag:land-ramp',
    description: 'Cards that fetch lands',
  },
  {
    pattern: /\bland\s+acceleration\b/gi,
    syntax: 'otag:ramp',
    description: 'Mana acceleration',
  },
  {
    pattern: /\bramp(?:ing)?\s+spells?\b/gi,
    syntax: 'otag:ramp',
    description: 'Mana ramp cards',
  },

  // Card advantage terms (NOT otag:card-advantage)
  {
    pattern: /\bcard\s+advantage\b/gi,
    syntax: 'otag:card-draw',
    description: 'Card draw effects',
  },
  {
    pattern: /\bdraw\s+engines?\b/gi,
    syntax: 'otag:card-draw',
    description: 'Repeatable card draw',
  },

  // Protection/Interaction (NOT otag:protection - that's about the keyword)
  {
    pattern: /\bspot\s+removal\b/gi,
    syntax: 'otag:spot-removal',
    description: 'Single-target removal',
  },
  {
    pattern: /\bmass\s+removal\b/gi,
    syntax: 'otag:mass-removal',
    description: 'Multi-target or board removal',
  },
  {
    pattern: /\bsweepers?\b/gi,
    syntax: 'otag:board-wipe',
    description: 'Board wipe effects',
  },

  // Combat tricks (NOT otag:combat - use combat-trick)
  {
    pattern: /\bcombat\s+tricks?\b/gi,
    syntax: 'otag:combat-trick',
    description: 'Instant-speed combat modifiers',
  },
  {
    pattern: /\bpump\s+spells?\b/gi,
    syntax: 'otag:pump',
    description: 'Power/toughness boosting spells',
  },

  // Finishers/Win conditions (NOT otag:finisher)
  {
    pattern: /\bfinishers?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending threats',
  },
  {
    pattern: /\bgame\s+enders?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending cards',
  },
  {
    pattern: /\balt(?:ernate)?\s+win(?:\s+con(?:dition)?s?)?\b/gi,
    syntax: 'o:"you win the game"',
    description: 'Alternate win conditions',
  },

  // Disruption (NOT otag:disruption)
  {
    pattern: /\bhand\s+disruption\b/gi,
    syntax: 'otag:discard-outlet',
    description: 'Discard effects',
  },
  {
    pattern: /\bhand\s+attack\b/gi,
    syntax: 'o:"discard" o:"opponent"',
    description: 'Forced discard effects',
  },

  // Recursion terms (NOT otag:recursion - use graveyard-recursion)
  {
    pattern: /\brecursion\b/gi,
    syntax: 'otag:graveyard-recursion',
    description: 'Return cards from graveyard',
  },
  {
    pattern: /\bgraveyard\s+recursion\b/gi,
    syntax: 'otag:graveyard-recursion',
    description: 'Return cards from graveyard',
  },
  {
    pattern: /\breanimate\b/gi,
    syntax: 'otag:reanimation',
    description: 'Return creatures from graveyard to battlefield',
  },

  // Token-related (NOT otag:tokens - use token-generator)
  {
    pattern: /\btoken\s+makers?\b/gi,
    syntax: 'otag:token-generator',
    description: 'Cards that create tokens',
  },
  {
    pattern: /\btoken\s+production\b/gi,
    syntax: 'otag:token-generator',
    description: 'Cards that create tokens',
  },
  {
    pattern: /\bgo\s+wide\b/gi,
    syntax: 'otag:token-generator',
    description: 'Token/swarm strategy',
  },

  // Evasion (NOT otag:evasion - compound search)
  {
    pattern: /\bevasion\b/gi,
    syntax:
      '(kw:flying or kw:menace or kw:skulk or kw:shadow or kw:fear or kw:intimidate or kw:horsemanship or o:"can\'t be blocked")',
    description: 'Creatures with evasion abilities',
  },
  {
    pattern: /\bunblockable\b/gi,
    syntax: 'o:"can\'t be blocked"',
    description: 'Cannot be blocked',
  },

  // Burn (otag:burn exists but adding common variations)
  {
    pattern: /\bdirect\s+damage\b/gi,
    syntax: 'otag:burn',
    description: 'Direct damage spells',
  },
  {
    pattern: /\bface\s+damage\b/gi,
    syntax: 'o:"damage" (o:"opponent" or o:"player")',
    description: 'Damage to players',
  },

  // ETB/LTB triggers
  {
    pattern: /\betb\s+(?:trigger|effect)s?\b/gi,
    syntax: 'otag:etb-trigger',
    description: 'Enter the battlefield triggers',
  },
  {
    pattern: /\bltb\s+(?:trigger|effect)s?\b/gi,
    syntax: 'otag:ltb-trigger',
    description: 'Leave the battlefield triggers',
  },
  {
    pattern: /\bdeath\s+triggers?\b/gi,
    syntax: 'otag:death-trigger',
    description: 'Dies triggers',
  },

  // Miscellaneous common slang
  {
    pattern: /\bping(?:ers?)?\b/gi,
    syntax: 'otag:ping',
    description: 'Small damage effects',
  },
  {
    pattern: /\bdrain(?:ers?)?\b/gi,
    syntax: 'otag:drain',
    description: 'Life drain effects',
  },
  {
    pattern: /\btax\s+effects?\b/gi,
    syntax: 'otag:tax-effect',
    description: 'Tax/pay more effects',
  },
  {
    pattern: /\blords?\b/gi,
    syntax: 'otag:lord',
    description: 'Creature type buffers',
  },
  {
    pattern: /\banthems?\b/gi,
    syntax: 'otag:anthem',
    description: 'Team-wide buffs',
  },
];
