/**
 * Slang-to-Scryfall syntax mappings for common MTG terms.
 * These terms are often incorrectly generated by AI as invalid oracle tags (otag:).
 * Maps slang terms to valid Scryfall syntax.
 * @module mappings/slang-to-syntax
 */

export interface SlangMapping {
  /** Pattern to match the slang term */
  pattern: RegExp;
  /** Valid Scryfall syntax to use instead */
  syntax: string;
  /** Description for debugging/logs */
  description?: string;
}

/**
 * Slang terms that should NOT become otag: values.
 * The AI often incorrectly generates these as otag:counterspell, otag:aggro, etc.
 * This layer intercepts them and converts to valid Scryfall syntax.
 */
export const SLANG_TO_SYNTAX_MAP: SlangMapping[] = [
  // Counter magic (use oracle text search for reliability)
  {
    pattern: /\bcounterspells?\b/gi,
    syntax: 't:instant o:"counter target"',
    description: 'Counter target spell effects',
  },
  {
    pattern: /\bcounter ?magics?\b/gi,
    syntax: 't:instant o:"counter target"',
    description: 'Counter target spell effects',
  },
  {
    pattern: /\bspell counters?\b/gi,
    syntax: 't:instant o:"counter target"',
    description: 'Counter target spell effects',
  },

  // Aggro/Beatdown (NOT otag:aggro - that doesn't exist)
  {
    pattern: /\baggro\s+(?:creature|deck|cards?)?\b/gi,
    syntax: 't:creature mv<=3 pow>=2',
    description: 'Low-cost aggressive creatures',
  },
  {
    pattern: /\bbeatdown\b/gi,
    syntax: 't:creature pow>=3',
    description: 'High power creatures for attacking',
  },
  {
    pattern: /\bweenies?\b/gi,
    syntax: 't:creature mv<=2',
    description: 'Small cheap creatures',
  },

  // Sacrifice effects (NOT otag:sacrifice - use sacrifice-outlet)
  {
    pattern: /\bsac(?:rifice)?\s+outlets?\b/gi,
    syntax: 'otag:sacrifice-outlet',
    description: 'Cards that let you sacrifice permanents',
  },
  {
    pattern: /\bfree\s+sac(?:rifice)?\s+outlets?\b/gi,
    syntax: 'otag:free-sacrifice-outlet',
    description: 'Free sacrifice outlets (no mana cost)',
  },

  // Ramp variations (otag:land-ramp doesn't exist - use ramp or oracle text)
  {
    pattern: /\bland\s+fetching\b/gi,
    syntax: 'o:"search" o:"library" o:"land"',
    description: 'Cards that fetch lands',
  },
  {
    pattern: /\bland\s+acceleration\b/gi,
    syntax: 'otag:ramp',
    description: 'Mana acceleration',
  },
  {
    pattern: /\bramp(?:ing)?\s+spells?\b/gi,
    syntax: 'otag:ramp',
    description: 'Mana ramp cards',
  },

  // Card advantage terms (otag:card-draw doesn't exist - use oracle text)
  {
    pattern: /\bcard\s+advantage\b/gi,
    syntax: 'o:"draw" (o:"card" or o:"cards")',
    description: 'Card draw effects',
  },
  {
    pattern: /\bdraw\s+engines?\b/gi,
    syntax: 'o:"whenever" o:"draw"',
    description: 'Repeatable card draw',
  },

  // Protection/Interaction (NOT otag:protection - that's about the keyword)
  {
    pattern: /\bspot\s+removal\b/gi,
    syntax: 'otag:spot-removal',
    description: 'Single-target removal',
  },
  {
    pattern: /\bmass\s+removal\b/gi,
    syntax: 'otag:mass-removal',
    description: 'Multi-target or board removal',
  },
  {
    pattern: /\bsweepers?\b/gi,
    syntax: 'otag:board-wipe',
    description: 'Board wipe effects',
  },

  // Combat tricks (NOT otag:combat - use combat-trick)
  {
    pattern: /\bcombat\s+tricks?\b/gi,
    syntax: 'otag:combat-trick',
    description: 'Instant-speed combat modifiers',
  },

  // Finishers/Win conditions (NOT otag:finisher)
  {
    pattern: /\bfinishers?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending threats',
  },
  {
    pattern: /\bgame\s+enders?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending cards',
  },
  {
    pattern: /\balt(?:ernate)?\s+win(?:\s+con(?:dition)?s?)?\b/gi,
    syntax: 'o:"you win the game"',
    description: 'Alternate win conditions',
  },

  // Disruption (NOT otag:disruption)
  {
    pattern: /\bhand\s+disruption\b/gi,
    syntax: 'otag:discard-outlet',
    description: 'Discard effects',
  },
  {
    pattern: /\bhand\s+attack\b/gi,
    syntax: 'o:"discard" o:"opponent"',
    description: 'Forced discard effects',
  },

  // Recursion terms (otag:graveyard-recursion doesn't exist - use recursion)
  {
    pattern: /\brecursion\b/gi,
    syntax: 'otag:recursion',
    description: 'Return cards from graveyard',
  },
  {
    pattern: /\bgraveyard\s+recursion\b/gi,
    syntax: 'otag:recursion',
    description: 'Return cards from graveyard',
  },
  {
    pattern: /\breanimate\b/gi,
    syntax: 'o:"return" o:"creature" o:"graveyard" o:"battlefield"',
    description: 'Return creatures from graveyard to battlefield',
  },

  // Token-related (otag:token-generator doesn't exist - use oracle text)
  {
    pattern: /\btoken\s+makers?\b/gi,
    syntax: 'o:"create" o:"token"',
    description: 'Cards that create tokens',
  },
  {
    pattern: /\btoken\s+production\b/gi,
    syntax: 'o:"create" o:"token"',
    description: 'Cards that create tokens',
  },
  {
    pattern: /\bgo\s+wide\b/gi,
    syntax: 'o:"create" (o:"tokens" or o:"creature tokens")',
    description: 'Token/swarm strategy',
  },

  // Evasion (NOT otag:evasion - compound search)
  {
    pattern: /\bevasion\b/gi,
    syntax:
      '(kw:flying or kw:menace or kw:skulk or kw:shadow or kw:fear or kw:intimidate or kw:horsemanship or o:"can\'t be blocked")',
    description: 'Creatures with evasion abilities',
  },
  {
    pattern: /\bunblockable\b/gi,
    syntax: 'o:"can\'t be blocked"',
    description: 'Cannot be blocked',
  },

  // Burn (otag:burn exists but adding common variations)
  {
    pattern: /\bdirect\s+damage\b/gi,
    syntax: 'otag:burn',
    description: 'Direct damage spells',
  },
  {
    pattern: /\bface\s+damage\b/gi,
    syntax: 'o:"damage" (o:"opponent" or o:"player")',
    description: 'Damage to players',
  },

  // ETB/LTB triggers (NOT otag:etb-trigger/ltb-trigger - those don't exist)
  {
    pattern: /\betb\s+(?:trigger|effect)s?\b/gi,
    syntax: 'o:"enters the battlefield"',
    description: 'Enter the battlefield triggers',
  },
  {
    pattern: /\bltb\s+(?:trigger|effect)s?\b/gi,
    syntax: 'o:"leaves the battlefield"',
    description: 'Leave the battlefield triggers',
  },
  {
    pattern: /\bdeath\s+triggers?\b/gi,
    syntax: 'otag:death-trigger',
    description: 'Dies triggers',
  },

  // Miscellaneous common slang
  {
    pattern: /\bping(?:ers?)?\b/gi,
    syntax: 'o:"deals 1 damage"',
    description: 'Small damage effects',
  },
  {
    pattern: /\bdrain(?:ers?)?\b/gi,
    syntax: '(o:"loses" o:"life" o:"gains" or o:"deals" o:"damage" o:"gains")',
    description: 'Life drain effects',
  },
  {
    pattern: /\btax\s+effects?\b/gi,
    syntax: '(o:"pay" o:"additional" or o:"costs" o:"more")',
    description: 'Tax/pay more effects',
  },
  {
    pattern: /\blords?\b/gi,
    syntax: 'otag:lord',
    description: 'Creature type buffers',
  },
  {
    pattern: /\banthems?\b/gi,
    syntax: 'otag:anthem',
    description: 'Team-wide buffs',
  },
  {
    pattern: /\bpump\s+spells?\b/gi,
    syntax: 'o:/\\+[0-9]+\\/\\+[0-9]+/',
    description: 'Power/toughness boosting spells',
  },

  // Strategy archetypes
  {
    pattern: /\bvoltron\b/gi,
    syntax: '(t:equipment or t:aura or o:"equipped creature" or o:"enchanted creature")',
    description: 'Equipment/aura strategy',
  },
  {
    pattern: /\bstorm\s+count\b/gi,
    syntax: 'kw:storm',
    description: 'Storm mechanic cards',
  },
  {
    pattern: /\bmana\s+base\b/gi,
    syntax: 't:land (o:"add {" or t:basic)',
    description: 'Lands for mana production',
  },
  {
    pattern: /\bmana\s+curve\b/gi,
    syntax: 't:creature mv<=3',
    description: 'Cheap creatures for curve',
  },
  {
    pattern: /\bstax\s+(?:piece|card)?s?\b/gi,
    syntax: '(o:"can\'t" o:"unless" or o:"additional" o:"cost" or o:"must" o:"attack")',
    description: 'Stax/tax prison effects',
  },
  {
    pattern: /\bprison\s+(?:piece|card)?s?\b/gi,
    syntax: '(o:"can\'t" or o:"must" o:"sacrifice" or o:"skip")',
    description: 'Prison/lock effects',
  },
  {
    pattern: /\bhate\s+bears?\b/gi,
    syntax: 't:creature mv<=3 (o:"can\'t" or o:"costs" o:"more")',
    description: 'Hatebear creatures',
  },
  {
    pattern: /\bvalue\s+engines?\b/gi,
    syntax: '(otag:card-draw or o:"whenever" o:"draw")',
    description: 'Card advantage engines',
  },
  {
    pattern: /\bflicker(?:ing)?\s+(?:effect|spell)?s?\b/gi,
    syntax: 'otag:flicker',
    description: 'Exile and return effects',
  },
  {
    pattern: /\bblink\s+(?:effect|spell)?s?\b/gi,
    syntax: 'otag:flicker',
    description: 'Exile and return effects',
  },
  {
    pattern: /\bclones?\b/gi,
    syntax: 'otag:clone',
    description: 'Copy creature effects',
  },
  {
    pattern: /\binfect\s+creatures?\b/gi,
    syntax: 'kw:infect t:creature',
    description: 'Creatures with infect',
  },
  {
    pattern: /\bpoisonous?\s+creatures?\b/gi,
    syntax: '(kw:infect or kw:toxic) t:creature',
    description: 'Poison-dealing creatures',
  },

  // NEW: Common MTG slang terms
  {
    pattern: /\bcantrips?\b/gi,
    syntax: 'otag:cantrip',
    description: 'Spells that draw a card',
  },
  {
    pattern: /\bfinishers?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending threats',
  },
  {
    pattern: /\bgame\s+enders?\b/gi,
    syntax: 'otag:win-condition',
    description: 'Game-ending cards',
  },
  {
    pattern: /\balt(?:ernate)?\s+win(?:\s+con(?:dition)?s?)?\b/gi,
    syntax: 'o:"you win the game"',
    description: 'Alternate win conditions',
  },
  {
    pattern: /\btech\s+cards?\b/gi,
    syntax: '(o:"can\'t" or o:"protection from" or o:"exile" o:"graveyard")',
    description: 'Sideboard/tech cards',
  },
  {
    pattern: /\bsilver\s+bullets?\b/gi,
    syntax: '(o:"can\'t" or o:"protection from" or o:"whenever" o:"opponent")',
    description: 'Narrow hate cards',
  },
  {
    pattern: /\bcombo\s+(?:piece|enabler|card)?s?\b/gi,
    syntax: '(o:"untap" o:"creature" or o:"infinite" or o:"mana" o:"add" or kw:storm)',
    description: 'Combo enabling cards',
  },
  {
    pattern: /\bsac(?:rifice)?\s+fodder\b/gi,
    syntax: '(o:"dies" o:"create" or o:"when" o:"dies" or t:creature mv<=2)',
    description: 'Cheap creatures to sacrifice',
  },
  {
    pattern: /\brecurring\s+threats?\b/gi,
    syntax: '(o:"return" o:"from" o:"graveyard" o:"battlefield" or o:"escape")',
    description: 'Self-recurring creatures',
  },
  {
    pattern: /\bsac\s+payoffs?\b/gi,
    syntax: 'o:"whenever" (o:"sacrificed" or o:"dies")',
    description: 'Benefits from sacrificing',
  },
  {
    pattern: /\bdeath\s+payoffs?\b/gi,
    syntax: 'o:"whenever" (o:"creature" o:"dies" or o:"dies")',
    description: 'Benefits from creatures dying',
  },
  {
    pattern: /\bgrave(?:yard)?\s+hate\b/gi,
    syntax: '(o:"exile" o:"graveyard" or o:"exile" o:"graveyards")',
    description: 'Graveyard hate cards',
  },
  {
    pattern: /\bartifact\s+hate\b/gi,
    syntax: 'o:"destroy" (o:"artifact" or o:"artifacts")',
    description: 'Artifact destruction',
  },
  {
    pattern: /\benchantment\s+hate\b/gi,
    syntax: 'o:"destroy" (o:"enchantment" or o:"enchantments")',
    description: 'Enchantment destruction',
  },
  {
    pattern: /\bcreature\s+hate\b/gi,
    syntax: 'o:"destroy" o:"creature"',
    description: 'Creature destruction',
  },
  {
    pattern: /\bplaneswalker\s+hate\b/gi,
    syntax: '(o:"destroy" o:"planeswalker" or o:"damage" o:"planeswalker")',
    description: 'Planeswalker removal',
  },
  {
    pattern: /\bblood\s+artists?\b/gi,
    syntax: 'o:"whenever" (o:"dies" or o:"creature" o:"dies") o:"loses" o:"life"',
    description: 'Drain on death effects (like Blood Artist)',
  },
  {
    pattern: /\baristocrats?\b/gi,
    syntax: 'o:"whenever" (o:"dies" or o:"sacrificed")',
    description: 'Sacrifice synergy cards',
  },
  {
    pattern: /\bspellslinger\b/gi,
    syntax: 'o:"whenever" o:"cast" (o:"instant" or o:"sorcery")',
    description: 'Instant/sorcery synergy',
  },
  {
    pattern: /\bmagecraft\b/gi,
    syntax: 'o:"whenever" o:"cast" (o:"instant" or o:"sorcery")',
    description: 'Spell cast triggers',
  },
  {
    pattern: /\bselfmill\b/gi,
    syntax: 'o:"mill" o:"cards"',
    description: 'Self-mill effects',
  },
  {
    pattern: /\bself\s+mill\b/gi,
    syntax: 'o:"mill" o:"cards"',
    description: 'Self-mill effects',
  },
  {
    pattern: /\blooters?\b/gi,
    syntax: 'o:"draw" o:"discard"',
    description: 'Draw then discard effects',
  },
  {
    pattern: /\brummage(?:rs?)?\b/gi,
    syntax: 'o:"discard" o:"draw"',
    description: 'Discard then draw effects',
  },
  {
    pattern: /\btimmy\s+cards?\b/gi,
    syntax: 't:creature mv>=6 pow>=6',
    description: 'Big splashy creatures',
  },
  {
    pattern: /\bbig\s+dumb\s+creatures?\b/gi,
    syntax: 't:creature mv>=5 pow>=5',
    description: 'Large vanilla-ish creatures',
  },
  {
    pattern: /\bbeaters?\b/gi,
    syntax: 't:creature pow>=4',
    description: 'High power creatures',
  },
  {
    pattern: /\bbig\s+mana\b/gi,
    syntax: '(otag:ramp or o:"add" o:"{C}{C}" or o:"add" o:"any" o:"color")',
    description: 'Big mana generation',
  },
  {
    pattern: /\bfast\s+mana\b/gi,
    syntax: '(otag:ritual or o:"add" mv<=1)',
    description: 'Quick mana acceleration',
  },
  {
    pattern: /\bslot\s+machine\b/gi,
    syntax: 'o:"flip" o:"coin"',
    description: 'Coin flip effects',
  },
  {
    pattern: /\bchaos\s+cards?\b/gi,
    syntax: '(o:"coin" or o:"random" or o:"chaos")',
    description: 'Random/chaotic effects',
  },
  {
    pattern: /\bgroup\s+hug\b/gi,
    syntax: 'o:"each player" (o:"draws" or o:"gains" or o:"may")',
    description: 'Symmetric benefit effects',
  },
  {
    pattern: /\bpillowfort\b/gi,
    syntax: '(o:"can\'t attack you" or o:"can\'t be attacked" or o:"protection" or o:"prevent" o:"damage")',
    description: 'Defensive/deterrent effects',
  },
  {
    pattern: /\binfinity\s+combo\b/gi,
    syntax: '(o:"untap" o:"add" or o:"whenever" o:"add" o:"mana")',
    description: 'Infinite combo pieces',
  },
  {
    pattern: /\bmana\s+sink\b/gi,
    syntax: 'o:"{X}" (o:"draw" or o:"damage" or o:"tokens" or o:"+1/+1")',
    description: 'X-cost mana sinks',
  },
  {
    pattern: /\bx\s+spells?\b/gi,
    syntax: 'mana:X',
    description: 'Spells with X in cost',
  },
  {
    pattern: /\blandfall\b/gi,
    syntax: '(otag:landfall or otag:extra-land)',
    description: 'Landfall triggers and extra land drops',
  },
  {
    pattern: /\bchaos\b/gi,
    syntax: '(o:"coin" or o:"random" or o:"chaos")',
    description: 'Chaos and randomness effects',
  },
  {
    pattern: /\bcoin\s+flips?\b/gi,
    syntax: 'o:"flip a coin"',
    description: 'Coin flip cards',
  },
];
