// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-cards.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.3.6";
const search_cards_default = defineTool({
  name: "search_cards",
  title: "Search MTG cards",
  description: 'Search Magic: The Gathering cards using Scryfall search syntax (e.g. "o:draw c:u mv<=2 f:commander"). Returns up to 20 matching cards with name, mana cost, type line, oracle text, prices, and image URL.',
  inputSchema: {
    query: z.string().trim().min(1).max(500).describe('Scryfall-syntax query. Example: "o:treasure c:r mv<=2".'),
    unique: z.enum(["cards", "art", "prints"]).optional().describe('Deduplication mode. Defaults to "cards".'),
    order: z.enum(["name", "released", "usd", "edhrec", "cmc", "power", "toughness"]).optional().describe('Sort order. Defaults to "name".')
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ query, unique, order }) => {
    const scryfallQuery = /\bgame:/i.test(query) ? query : `${query} game:paper`;
    const params = new URLSearchParams({
      q: scryfallQuery,
      unique: unique ?? "cards",
      order: order ?? "name"
    });
    const res = await fetch(`https://api.scryfall.com/cards/search?${params}`, {
      headers: { Accept: "application/json" }
    });
    if (res.status === 404) {
      return {
        content: [
          {
            type: "text",
            text: `No cards found for query: ${scryfallQuery}`
          }
        ],
        structuredContent: { total: 0, cards: [] }
      };
    }
    if (!res.ok) {
      const body = await res.text();
      return {
        content: [
          {
            type: "text",
            text: `Scryfall error [${res.status}]: ${body.slice(0, 500)}`
          }
        ],
        isError: true
      };
    }
    const data = await res.json();
    const cards = (data.data ?? []).slice(0, 20).map((c) => ({
      name: c.name,
      mana_cost: c.mana_cost ?? "",
      type_line: c.type_line ?? "",
      oracle_text: c.oracle_text ?? "",
      price_usd: c.prices?.usd ?? null,
      price_eur: c.prices?.eur ?? null,
      image_url: c.image_uris?.normal ?? null,
      scryfall_url: c.scryfall_uri ?? null
    }));
    return {
      content: [
        {
          type: "text",
          text: `Found ${data.total_cards ?? cards.length} cards. Showing ${cards.length}.`
        }
      ],
      structuredContent: { total: data.total_cards ?? cards.length, cards }
    };
  }
});

// src/lib/mcp/tools/list-my-decks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.3.6";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
const list_my_decks_default = defineTool2({
  name: "list_my_decks",
  title: "List my decks",
  description: "List the signed-in user's decks (name, format, commander, card count, public/private, updated_at). Use get_deck for full card lists.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Default 25."),
    format: z2.string().max(50).optional().describe('Filter to one format, e.g. "commander".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, format }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("decks").select(
      "id, name, format, commander_name, color_identity, card_count, is_public, updated_at"
    ).eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (format) query = query.eq("format", format);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${data?.length ?? 0} deck(s).`
        }
      ],
      structuredContent: { decks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-deck.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.3.6";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
const get_deck_default = defineTool3({
  name: "get_deck",
  title: "Get deck details",
  description: "Fetch a deck (metadata + full card list grouped by board) the signed-in user owns or that is marked public.",
  inputSchema: {
    deck_id: z3.string().uuid().describe("Deck UUID from list_my_decks.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deck_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: deck, error: deckErr } = await supabase.from("decks").select(
      "id, name, format, commander_name, companion_name, color_identity, description, is_public, card_count, updated_at, user_id"
    ).eq("id", deck_id).maybeSingle();
    if (deckErr) {
      return {
        content: [{ type: "text", text: deckErr.message }],
        isError: true
      };
    }
    if (!deck) {
      return {
        content: [{ type: "text", text: "Deck not found or not accessible." }],
        isError: true
      };
    }
    const { data: cards, error: cardsErr } = await supabase.from("deck_cards").select("card_name, quantity, board, category").eq("deck_id", deck_id).order("board").order("card_name");
    if (cardsErr) {
      return {
        content: [{ type: "text", text: cardsErr.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `${deck.name} \u2014 ${deck.format} \u2014 ${cards?.length ?? 0} unique cards.`
        }
      ],
      structuredContent: { deck, cards: cards ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-saved-searches.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.3.6";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
const list_saved_searches_default = defineTool4({
  name: "list_saved_searches",
  title: "List saved searches",
  description: "List the signed-in user's saved natural-language searches with their translated Scryfall queries.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("saved_searches").select("id, natural_query, scryfall_query, label, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: `Found ${data?.length ?? 0} saved search(es).` }
      ],
      structuredContent: { saved_searches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-collection-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
const get_collection_summary_default = defineTool5({
  name: "get_collection_summary",
  title: "Get collection summary",
  description: "Return summary stats for the signed-in user's Magic card collection: unique cards, total cards, estimated USD value.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.rpc("get_public_collection_stats", {
      target_user_id: ctx.getUserId()
    });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Collection summary: ${JSON.stringify(data)}`
        }
      ],
      structuredContent: { summary: data }
    };
  }
});

// src/lib/mcp/index.ts
const projectRef = "nxmzyykkzwomkcentctt";
const mcp_default = defineMcp({
  name: "offmeta-mcp",
  title: "OffMeta",
  version: "0.1.0",
  instructions: "Tools for OffMeta, a natural-language Magic: The Gathering card search app. `search_cards` runs Scryfall syntax queries (append game:paper is automatic). The other tools read the signed-in user's decks, saved searches, and collection stats. All user tools require the caller to be signed in via OAuth.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_cards_default,
    list_my_decks_default,
    get_deck_default,
    list_saved_searches_default,
    get_collection_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
