name: Discord - PR Approvals

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-discord:
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/discord-notify.yml
    with:
      content: |-
        [PASS] PR Approved in `${{ github.repository }}`
        #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
        Approver: ${{ github.event.review.user.login }}
        Author: ${{ github.event.pull_request.user.login }}
        Branch: `${{ github.event.pull_request.head.ref }}` -> `${{ github.event.pull_request.base.ref }}`
        ${{ github.event.pull_request.html_url }}
    secrets: inherit
