name: Discord - PR Merged

on:
  pull_request:
    types: [closed]

jobs:
  notify-discord:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/discord-notify.yml
    with:
      content: |-
        [ROCKET] PR Merged in `${{ github.repository }}`
        #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
        Merged by: ${{ github.actor }}
        Branch: `${{ github.event.pull_request.head.ref }}` -> `${{ github.event.pull_request.base.ref }}`
        ${{ github.event.pull_request.html_url }}
    secrets: inherit
